//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Seguridad {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.ComponentModel.ToolboxItem(true)]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [System.Xml.Serialization.XmlRootAttribute("dsPermisos")]
    [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dsPermisos : System.Data.DataSet {
        
        private v_PermisosDataTable tablev_Permisos;
        
        private System.Data.SchemaSerializationMode _schemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public dsPermisos() {
            this.BeginInit();
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected dsPermisos(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == System.Data.SchemaSerializationMode.IncludeSchema)) {
                System.Data.DataSet ds = new System.Data.DataSet();
                ds.ReadXmlSchema(new System.Xml.XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["v_Permisos"] != null)) {
                    base.Tables.Add(new v_PermisosDataTable(ds.Tables["v_Permisos"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new System.Xml.XmlTextReader(new System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public v_PermisosDataTable v_Permisos {
            get {
                return this.tablev_Permisos;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.BrowsableAttribute(true)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override System.Data.DataSet Clone() {
            dsPermisos cln = ((dsPermisos)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                System.Data.DataSet ds = new System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["v_Permisos"] != null)) {
                    base.Tables.Add(new v_PermisosDataTable(ds.Tables["v_Permisos"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new System.Xml.XmlTextReader(stream), null);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tablev_Permisos = ((v_PermisosDataTable)(base.Tables["v_Permisos"]));
            if ((initTable == true)) {
                if ((this.tablev_Permisos != null)) {
                    this.tablev_Permisos.InitVars();
                }
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "dsPermisos";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsPermisos.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            this.tablev_Permisos = new v_PermisosDataTable();
            base.Tables.Add(this.tablev_Permisos);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializev_Permisos() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(System.Xml.Schema.XmlSchemaSet xs) {
            dsPermisos ds = new dsPermisos();
            System.Xml.Schema.XmlSchemaComplexType type = new System.Xml.Schema.XmlSchemaComplexType();
            System.Xml.Schema.XmlSchemaSequence sequence = new System.Xml.Schema.XmlSchemaSequence();
            xs.Add(ds.GetSchemaSerializable());
            System.Xml.Schema.XmlSchemaAny any = new System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            return type;
        }
        
        public delegate void v_PermisosRowChangeEventHandler(object sender, v_PermisosRowChangeEvent e);
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [System.Serializable()]
        [System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class v_PermisosDataTable : System.Data.DataTable, System.Collections.IEnumerable {
            
            private System.Data.DataColumn columnseguridadPerfilID;
            
            private System.Data.DataColumn columnseguridadOperacionID;
            
            private System.Data.DataColumn columnseguridadObjetoID;
            
            private System.Data.DataColumn columnoperacion_nombre;
            
            private System.Data.DataColumn columnoperacion_descripcion;
            
            private System.Data.DataColumn columnmoduloSistemaID;
            
            private System.Data.DataColumn columnobjeto_descripcion;
            
            private System.Data.DataColumn columnobjeto_identificador;
            
            private System.Data.DataColumn columnobjeto_nombre;
            
            private System.Data.DataColumn columnmodulo_nombre;
            
            private System.Data.DataColumn columnid;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public v_PermisosDataTable() {
                this.TableName = "v_Permisos";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal v_PermisosDataTable(System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected v_PermisosDataTable(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn seguridadPerfilIDColumn {
                get {
                    return this.columnseguridadPerfilID;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn seguridadOperacionIDColumn {
                get {
                    return this.columnseguridadOperacionID;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn seguridadObjetoIDColumn {
                get {
                    return this.columnseguridadObjetoID;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn operacion_nombreColumn {
                get {
                    return this.columnoperacion_nombre;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn operacion_descripcionColumn {
                get {
                    return this.columnoperacion_descripcion;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn moduloSistemaIDColumn {
                get {
                    return this.columnmoduloSistemaID;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn objeto_descripcionColumn {
                get {
                    return this.columnobjeto_descripcion;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn objeto_identificadorColumn {
                get {
                    return this.columnobjeto_identificador;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn objeto_nombreColumn {
                get {
                    return this.columnobjeto_nombre;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn modulo_nombreColumn {
                get {
                    return this.columnmodulo_nombre;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn idColumn {
                get {
                    return this.columnid;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public v_PermisosRow this[int index] {
                get {
                    return ((v_PermisosRow)(this.Rows[index]));
                }
            }
            
            public event v_PermisosRowChangeEventHandler v_PermisosRowChanging;
            
            public event v_PermisosRowChangeEventHandler v_PermisosRowChanged;
            
            public event v_PermisosRowChangeEventHandler v_PermisosRowDeleting;
            
            public event v_PermisosRowChangeEventHandler v_PermisosRowDeleted;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Addv_PermisosRow(v_PermisosRow row) {
                this.Rows.Add(row);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public v_PermisosRow Addv_PermisosRow(string seguridadPerfilID, string seguridadOperacionID, string seguridadObjetoID, string operacion_nombre, string operacion_descripcion, string moduloSistemaID, string objeto_descripcion, string objeto_identificador, string objeto_nombre, string modulo_nombre, string id) {
                v_PermisosRow rowv_PermisosRow = ((v_PermisosRow)(this.NewRow()));
                rowv_PermisosRow.ItemArray = new object[] {
                        seguridadPerfilID,
                        seguridadOperacionID,
                        seguridadObjetoID,
                        operacion_nombre,
                        operacion_descripcion,
                        moduloSistemaID,
                        objeto_descripcion,
                        objeto_identificador,
                        objeto_nombre,
                        modulo_nombre,
                        id};
                this.Rows.Add(rowv_PermisosRow);
                return rowv_PermisosRow;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public virtual System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override System.Data.DataTable Clone() {
                v_PermisosDataTable cln = ((v_PermisosDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Data.DataTable CreateInstance() {
                return new v_PermisosDataTable();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnseguridadPerfilID = base.Columns["seguridadPerfilID"];
                this.columnseguridadOperacionID = base.Columns["seguridadOperacionID"];
                this.columnseguridadObjetoID = base.Columns["seguridadObjetoID"];
                this.columnoperacion_nombre = base.Columns["operacion_nombre"];
                this.columnoperacion_descripcion = base.Columns["operacion_descripcion"];
                this.columnmoduloSistemaID = base.Columns["moduloSistemaID"];
                this.columnobjeto_descripcion = base.Columns["objeto_descripcion"];
                this.columnobjeto_identificador = base.Columns["objeto_identificador"];
                this.columnobjeto_nombre = base.Columns["objeto_nombre"];
                this.columnmodulo_nombre = base.Columns["modulo_nombre"];
                this.columnid = base.Columns["id"];
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnseguridadPerfilID = new System.Data.DataColumn("seguridadPerfilID", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnseguridadPerfilID);
                this.columnseguridadOperacionID = new System.Data.DataColumn("seguridadOperacionID", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnseguridadOperacionID);
                this.columnseguridadObjetoID = new System.Data.DataColumn("seguridadObjetoID", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnseguridadObjetoID);
                this.columnoperacion_nombre = new System.Data.DataColumn("operacion_nombre", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnoperacion_nombre);
                this.columnoperacion_descripcion = new System.Data.DataColumn("operacion_descripcion", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnoperacion_descripcion);
                this.columnmoduloSistemaID = new System.Data.DataColumn("moduloSistemaID", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnmoduloSistemaID);
                this.columnobjeto_descripcion = new System.Data.DataColumn("objeto_descripcion", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnobjeto_descripcion);
                this.columnobjeto_identificador = new System.Data.DataColumn("objeto_identificador", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnobjeto_identificador);
                this.columnobjeto_nombre = new System.Data.DataColumn("objeto_nombre", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnobjeto_nombre);
                this.columnmodulo_nombre = new System.Data.DataColumn("modulo_nombre", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnmodulo_nombre);
                this.columnid = new System.Data.DataColumn("id", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnid);
                this.columnseguridadPerfilID.AllowDBNull = false;
                this.columnseguridadOperacionID.AllowDBNull = false;
                this.columnseguridadObjetoID.AllowDBNull = false;
                this.columnoperacion_nombre.AllowDBNull = false;
                this.columnoperacion_descripcion.AllowDBNull = false;
                this.columnmoduloSistemaID.AllowDBNull = false;
                this.columnobjeto_descripcion.AllowDBNull = false;
                this.columnobjeto_identificador.AllowDBNull = false;
                this.columnobjeto_nombre.AllowDBNull = false;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public v_PermisosRow Newv_PermisosRow() {
                return ((v_PermisosRow)(this.NewRow()));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Data.DataRow NewRowFromBuilder(System.Data.DataRowBuilder builder) {
                return new v_PermisosRow(builder);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Type GetRowType() {
                return typeof(v_PermisosRow);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.v_PermisosRowChanged != null)) {
                    this.v_PermisosRowChanged(this, new v_PermisosRowChangeEvent(((v_PermisosRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.v_PermisosRowChanging != null)) {
                    this.v_PermisosRowChanging(this, new v_PermisosRowChangeEvent(((v_PermisosRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.v_PermisosRowDeleted != null)) {
                    this.v_PermisosRowDeleted(this, new v_PermisosRowChangeEvent(((v_PermisosRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.v_PermisosRowDeleting != null)) {
                    this.v_PermisosRowDeleting(this, new v_PermisosRowChangeEvent(((v_PermisosRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Removev_PermisosRow(v_PermisosRow row) {
                this.Rows.Remove(row);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(System.Xml.Schema.XmlSchemaSet xs) {
                System.Xml.Schema.XmlSchemaComplexType type = new System.Xml.Schema.XmlSchemaComplexType();
                System.Xml.Schema.XmlSchemaSequence sequence = new System.Xml.Schema.XmlSchemaSequence();
                dsPermisos ds = new dsPermisos();
                xs.Add(ds.GetSchemaSerializable());
                System.Xml.Schema.XmlSchemaAny any1 = new System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                System.Xml.Schema.XmlSchemaAny any2 = new System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                System.Xml.Schema.XmlSchemaAttribute attribute1 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                System.Xml.Schema.XmlSchemaAttribute attribute2 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "v_PermisosDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                return type;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class v_PermisosRow : System.Data.DataRow {
            
            private v_PermisosDataTable tablev_Permisos;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal v_PermisosRow(System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tablev_Permisos = ((v_PermisosDataTable)(this.Table));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string seguridadPerfilID {
                get {
                    return ((string)(this[this.tablev_Permisos.seguridadPerfilIDColumn]));
                }
                set {
                    this[this.tablev_Permisos.seguridadPerfilIDColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string seguridadOperacionID {
                get {
                    return ((string)(this[this.tablev_Permisos.seguridadOperacionIDColumn]));
                }
                set {
                    this[this.tablev_Permisos.seguridadOperacionIDColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string seguridadObjetoID {
                get {
                    return ((string)(this[this.tablev_Permisos.seguridadObjetoIDColumn]));
                }
                set {
                    this[this.tablev_Permisos.seguridadObjetoIDColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string operacion_nombre {
                get {
                    return ((string)(this[this.tablev_Permisos.operacion_nombreColumn]));
                }
                set {
                    this[this.tablev_Permisos.operacion_nombreColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string operacion_descripcion {
                get {
                    return ((string)(this[this.tablev_Permisos.operacion_descripcionColumn]));
                }
                set {
                    this[this.tablev_Permisos.operacion_descripcionColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string moduloSistemaID {
                get {
                    return ((string)(this[this.tablev_Permisos.moduloSistemaIDColumn]));
                }
                set {
                    this[this.tablev_Permisos.moduloSistemaIDColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string objeto_descripcion {
                get {
                    return ((string)(this[this.tablev_Permisos.objeto_descripcionColumn]));
                }
                set {
                    this[this.tablev_Permisos.objeto_descripcionColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string objeto_identificador {
                get {
                    return ((string)(this[this.tablev_Permisos.objeto_identificadorColumn]));
                }
                set {
                    this[this.tablev_Permisos.objeto_identificadorColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string objeto_nombre {
                get {
                    return ((string)(this[this.tablev_Permisos.objeto_nombreColumn]));
                }
                set {
                    this[this.tablev_Permisos.objeto_nombreColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string modulo_nombre {
                get {
                    try {
                        return ((string)(this[this.tablev_Permisos.modulo_nombreColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'modulo_nombre\' in table \'v_Permisos\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Permisos.modulo_nombreColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string id {
                get {
                    try {
                        return ((string)(this[this.tablev_Permisos.idColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'id\' in table \'v_Permisos\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Permisos.idColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Ismodulo_nombreNull() {
                return this.IsNull(this.tablev_Permisos.modulo_nombreColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setmodulo_nombreNull() {
                this[this.tablev_Permisos.modulo_nombreColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsidNull() {
                return this.IsNull(this.tablev_Permisos.idColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetidNull() {
                this[this.tablev_Permisos.idColumn] = System.Convert.DBNull;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class v_PermisosRowChangeEvent : System.EventArgs {
            
            private v_PermisosRow eventRow;
            
            private System.Data.DataRowAction eventAction;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public v_PermisosRowChangeEvent(v_PermisosRow row, System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public v_PermisosRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591