-- ========================================
-- BÚSQUEDA DEL CAMPO HABILITADO EN OTRAS TABLAS
-- ========================================

-- 1. BUSCAR CAMPO HABILITADO EN TODAS LAS TABLAS DE LA BASE DE DATOS
SELECT 
    TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE COLUMN_NAME = 'habilitado'
  AND TABLE_SCHEMA = 'dbo'
ORDER BY TABLE_NAME

-- 2. VERIFICAR SI EXISTE TABLA RELACIONADA CON USUARIOS
SELECT 
    TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME LIKE '%usuario%'
  AND TABLE_SCHEMA = 'dbo'
ORDER BY TABLE_NAME, ORDINAL_POSITION

-- 3. VERIFICAR TABLA Usuario SI EXISTE
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    CHARACTER_MAXIMUM_LENGTH,
    COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Usuario' 
  AND TABLE_SCHEMA = 'dbo'
ORDER BY ORDINAL_POSITION

-- 4. BUSCAR RELACIÓN ENTRE PACIENTE Y USUARIO
SELECT 
    t.TABLE_NAME,
    k.COLUMN_NAME,
    k.REFERENCED_TABLE_NAME,
    k.REFERENCED_COLUMN_NAME
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS t
INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE k 
    ON t.CONSTRAINT_NAME = k.CONSTRAINT_NAME
WHERE t.TABLE_NAME = 'Paciente'
  AND t.CONSTRAINT_TYPE = 'FOREIGN KEY'

-- 5. VERIFICAR SI EXISTE ALGÚN CAMPO DE ESTADO EN PACIENTE
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Paciente' 
  AND TABLE_SCHEMA = 'dbo'
  AND (COLUMN_NAME LIKE '%estado%' 
       OR COLUMN_NAME LIKE '%activo%' 
       OR COLUMN_NAME LIKE '%status%'
       OR COLUMN_NAME LIKE '%habilit%')
ORDER BY COLUMN_NAME

-- 6. VERIFICAR DATOS DEL PACIENTE CON DNI 55676837
SELECT 
    id,
    dni,
    apellido,
    nombres,
    'Todos los campos disponibles' as Info
FROM dbo.Paciente 
WHERE dni = '55676837'

-- ========================================
-- ANÁLISIS:
-- El campo 'habilitado' no existe en la tabla Paciente
-- Probablemente el estado se maneja en otra tabla relacionada
-- ========================================
