//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Comunes {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.ComponentModel.ToolboxItem(true)]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [System.Xml.Serialization.XmlRootAttribute("dsFormaPagoLinea")]
    [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dsFormaPagoLinea : System.Data.DataSet {
        
        private v_FormaPagoLineaDataTable tablev_FormaPagoLinea;
        
        private System.Data.SchemaSerializationMode _schemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public dsFormaPagoLinea() {
            this.BeginInit();
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected dsFormaPagoLinea(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == System.Data.SchemaSerializationMode.IncludeSchema)) {
                System.Data.DataSet ds = new System.Data.DataSet();
                ds.ReadXmlSchema(new System.Xml.XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["v_FormaPagoLinea"] != null)) {
                    base.Tables.Add(new v_FormaPagoLineaDataTable(ds.Tables["v_FormaPagoLinea"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new System.Xml.XmlTextReader(new System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public v_FormaPagoLineaDataTable v_FormaPagoLinea {
            get {
                return this.tablev_FormaPagoLinea;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.BrowsableAttribute(true)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override System.Data.DataSet Clone() {
            dsFormaPagoLinea cln = ((dsFormaPagoLinea)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                System.Data.DataSet ds = new System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["v_FormaPagoLinea"] != null)) {
                    base.Tables.Add(new v_FormaPagoLineaDataTable(ds.Tables["v_FormaPagoLinea"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new System.Xml.XmlTextReader(stream), null);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tablev_FormaPagoLinea = ((v_FormaPagoLineaDataTable)(base.Tables["v_FormaPagoLinea"]));
            if ((initTable == true)) {
                if ((this.tablev_FormaPagoLinea != null)) {
                    this.tablev_FormaPagoLinea.InitVars();
                }
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "dsFormaPagoLinea";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsFormaPagoLinea.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            this.tablev_FormaPagoLinea = new v_FormaPagoLineaDataTable();
            base.Tables.Add(this.tablev_FormaPagoLinea);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializev_FormaPagoLinea() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(System.Xml.Schema.XmlSchemaSet xs) {
            dsFormaPagoLinea ds = new dsFormaPagoLinea();
            System.Xml.Schema.XmlSchemaComplexType type = new System.Xml.Schema.XmlSchemaComplexType();
            System.Xml.Schema.XmlSchemaSequence sequence = new System.Xml.Schema.XmlSchemaSequence();
            xs.Add(ds.GetSchemaSerializable());
            System.Xml.Schema.XmlSchemaAny any = new System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            return type;
        }
        
        public delegate void v_FormaPagoLineaRowChangeEventHandler(object sender, v_FormaPagoLineaRowChangeEvent e);
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [System.Serializable()]
        [System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class v_FormaPagoLineaDataTable : System.Data.DataTable, System.Collections.IEnumerable {
            
            private System.Data.DataColumn columnid;
            
            private System.Data.DataColumn columntipoPagoID;
            
            private System.Data.DataColumn columntipoPagoDetalleID;
            
            private System.Data.DataColumn columnimporte;
            
            private System.Data.DataColumn columnajuste;
            
            private System.Data.DataColumn columnpesos;
            
            private System.Data.DataColumn columnTipo_Pago;
            
            private System.Data.DataColumn columnidentificador;
            
            private System.Data.DataColumn columnoperacion;
            
            private System.Data.DataColumn _columnNro__Cheque;
            
            private System.Data.DataColumn columnbancoID;
            
            private System.Data.DataColumn columncantidadPagosID;
            
            private System.Data.DataColumn columnformaPagoID;
            
            private System.Data.DataColumn columnDetalle;
            
            private System.Data.DataColumn columnnotaCreditoID;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public v_FormaPagoLineaDataTable() {
                this.TableName = "v_FormaPagoLinea";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal v_FormaPagoLineaDataTable(System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected v_FormaPagoLineaDataTable(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn idColumn {
                get {
                    return this.columnid;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn tipoPagoIDColumn {
                get {
                    return this.columntipoPagoID;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn tipoPagoDetalleIDColumn {
                get {
                    return this.columntipoPagoDetalleID;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn importeColumn {
                get {
                    return this.columnimporte;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn ajusteColumn {
                get {
                    return this.columnajuste;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn pesosColumn {
                get {
                    return this.columnpesos;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Tipo_PagoColumn {
                get {
                    return this.columnTipo_Pago;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn identificadorColumn {
                get {
                    return this.columnidentificador;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn operacionColumn {
                get {
                    return this.columnoperacion;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn _Nro__ChequeColumn {
                get {
                    return this._columnNro__Cheque;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn bancoIDColumn {
                get {
                    return this.columnbancoID;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn cantidadPagosIDColumn {
                get {
                    return this.columncantidadPagosID;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn formaPagoIDColumn {
                get {
                    return this.columnformaPagoID;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn DetalleColumn {
                get {
                    return this.columnDetalle;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn notaCreditoIDColumn {
                get {
                    return this.columnnotaCreditoID;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public v_FormaPagoLineaRow this[int index] {
                get {
                    return ((v_FormaPagoLineaRow)(this.Rows[index]));
                }
            }
            
            public event v_FormaPagoLineaRowChangeEventHandler v_FormaPagoLineaRowChanging;
            
            public event v_FormaPagoLineaRowChangeEventHandler v_FormaPagoLineaRowChanged;
            
            public event v_FormaPagoLineaRowChangeEventHandler v_FormaPagoLineaRowDeleting;
            
            public event v_FormaPagoLineaRowChangeEventHandler v_FormaPagoLineaRowDeleted;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Addv_FormaPagoLineaRow(v_FormaPagoLineaRow row) {
                this.Rows.Add(row);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public v_FormaPagoLineaRow Addv_FormaPagoLineaRow(System.Guid id, System.Guid tipoPagoID, System.Guid tipoPagoDetalleID, decimal importe, decimal ajuste, decimal pesos, string Tipo_Pago, string identificador, string operacion, string _Nro__Cheque, System.Guid bancoID, System.Guid cantidadPagosID, System.Guid formaPagoID, string Detalle, System.Guid notaCreditoID) {
                v_FormaPagoLineaRow rowv_FormaPagoLineaRow = ((v_FormaPagoLineaRow)(this.NewRow()));
                rowv_FormaPagoLineaRow.ItemArray = new object[] {
                        id,
                        tipoPagoID,
                        tipoPagoDetalleID,
                        importe,
                        ajuste,
                        pesos,
                        Tipo_Pago,
                        identificador,
                        operacion,
                        _Nro__Cheque,
                        bancoID,
                        cantidadPagosID,
                        formaPagoID,
                        Detalle,
                        notaCreditoID};
                this.Rows.Add(rowv_FormaPagoLineaRow);
                return rowv_FormaPagoLineaRow;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public virtual System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override System.Data.DataTable Clone() {
                v_FormaPagoLineaDataTable cln = ((v_FormaPagoLineaDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Data.DataTable CreateInstance() {
                return new v_FormaPagoLineaDataTable();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnid = base.Columns["id"];
                this.columntipoPagoID = base.Columns["tipoPagoID"];
                this.columntipoPagoDetalleID = base.Columns["tipoPagoDetalleID"];
                this.columnimporte = base.Columns["importe"];
                this.columnajuste = base.Columns["ajuste"];
                this.columnpesos = base.Columns["pesos"];
                this.columnTipo_Pago = base.Columns["Tipo Pago"];
                this.columnidentificador = base.Columns["identificador"];
                this.columnoperacion = base.Columns["operacion"];
                this._columnNro__Cheque = base.Columns["Nro. Cheque"];
                this.columnbancoID = base.Columns["bancoID"];
                this.columncantidadPagosID = base.Columns["cantidadPagosID"];
                this.columnformaPagoID = base.Columns["formaPagoID"];
                this.columnDetalle = base.Columns["Detalle"];
                this.columnnotaCreditoID = base.Columns["notaCreditoID"];
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnid = new System.Data.DataColumn("id", typeof(System.Guid), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnid);
                this.columntipoPagoID = new System.Data.DataColumn("tipoPagoID", typeof(System.Guid), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columntipoPagoID);
                this.columntipoPagoDetalleID = new System.Data.DataColumn("tipoPagoDetalleID", typeof(System.Guid), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columntipoPagoDetalleID);
                this.columnimporte = new System.Data.DataColumn("importe", typeof(decimal), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnimporte);
                this.columnajuste = new System.Data.DataColumn("ajuste", typeof(decimal), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnajuste);
                this.columnpesos = new System.Data.DataColumn("pesos", typeof(decimal), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnpesos);
                this.columnTipo_Pago = new System.Data.DataColumn("Tipo Pago", typeof(string), null, System.Data.MappingType.Element);
                this.columnTipo_Pago.ExtendedProperties.Add("Generator_ColumnPropNameInRow", "Tipo_Pago");
                this.columnTipo_Pago.ExtendedProperties.Add("Generator_ColumnPropNameInTable", "Tipo_PagoColumn");
                this.columnTipo_Pago.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "columnTipo_Pago");
                this.columnTipo_Pago.ExtendedProperties.Add("Generator_UserColumnName", "Tipo Pago");
                base.Columns.Add(this.columnTipo_Pago);
                this.columnidentificador = new System.Data.DataColumn("identificador", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnidentificador);
                this.columnoperacion = new System.Data.DataColumn("operacion", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnoperacion);
                this._columnNro__Cheque = new System.Data.DataColumn("Nro. Cheque", typeof(string), null, System.Data.MappingType.Element);
                this._columnNro__Cheque.ExtendedProperties.Add("Generator_ColumnPropNameInRow", "_Nro__Cheque");
                this._columnNro__Cheque.ExtendedProperties.Add("Generator_ColumnPropNameInTable", "_Nro__ChequeColumn");
                this._columnNro__Cheque.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnNro__Cheque");
                this._columnNro__Cheque.ExtendedProperties.Add("Generator_UserColumnName", "Nro. Cheque");
                base.Columns.Add(this._columnNro__Cheque);
                this.columnbancoID = new System.Data.DataColumn("bancoID", typeof(System.Guid), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnbancoID);
                this.columncantidadPagosID = new System.Data.DataColumn("cantidadPagosID", typeof(System.Guid), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columncantidadPagosID);
                this.columnformaPagoID = new System.Data.DataColumn("formaPagoID", typeof(System.Guid), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnformaPagoID);
                this.columnDetalle = new System.Data.DataColumn("Detalle", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnDetalle);
                this.columnnotaCreditoID = new System.Data.DataColumn("notaCreditoID", typeof(System.Guid), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnnotaCreditoID);
                this.columnid.AllowDBNull = false;
                this.columnimporte.AllowDBNull = false;
                this.columnajuste.AllowDBNull = false;
                this.columnpesos.AllowDBNull = false;
                this.columnTipo_Pago.MaxLength = 256;
                this.columnidentificador.MaxLength = 50;
                this.columnoperacion.MaxLength = 50;
                this._columnNro__Cheque.AllowDBNull = false;
                this._columnNro__Cheque.MaxLength = 50;
                this.columnformaPagoID.AllowDBNull = false;
                this.columnDetalle.MaxLength = 255;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public v_FormaPagoLineaRow Newv_FormaPagoLineaRow() {
                return ((v_FormaPagoLineaRow)(this.NewRow()));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Data.DataRow NewRowFromBuilder(System.Data.DataRowBuilder builder) {
                return new v_FormaPagoLineaRow(builder);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Type GetRowType() {
                return typeof(v_FormaPagoLineaRow);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.v_FormaPagoLineaRowChanged != null)) {
                    this.v_FormaPagoLineaRowChanged(this, new v_FormaPagoLineaRowChangeEvent(((v_FormaPagoLineaRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.v_FormaPagoLineaRowChanging != null)) {
                    this.v_FormaPagoLineaRowChanging(this, new v_FormaPagoLineaRowChangeEvent(((v_FormaPagoLineaRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.v_FormaPagoLineaRowDeleted != null)) {
                    this.v_FormaPagoLineaRowDeleted(this, new v_FormaPagoLineaRowChangeEvent(((v_FormaPagoLineaRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.v_FormaPagoLineaRowDeleting != null)) {
                    this.v_FormaPagoLineaRowDeleting(this, new v_FormaPagoLineaRowChangeEvent(((v_FormaPagoLineaRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Removev_FormaPagoLineaRow(v_FormaPagoLineaRow row) {
                this.Rows.Remove(row);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(System.Xml.Schema.XmlSchemaSet xs) {
                System.Xml.Schema.XmlSchemaComplexType type = new System.Xml.Schema.XmlSchemaComplexType();
                System.Xml.Schema.XmlSchemaSequence sequence = new System.Xml.Schema.XmlSchemaSequence();
                dsFormaPagoLinea ds = new dsFormaPagoLinea();
                xs.Add(ds.GetSchemaSerializable());
                System.Xml.Schema.XmlSchemaAny any1 = new System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                System.Xml.Schema.XmlSchemaAny any2 = new System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                System.Xml.Schema.XmlSchemaAttribute attribute1 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                System.Xml.Schema.XmlSchemaAttribute attribute2 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "v_FormaPagoLineaDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                return type;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class v_FormaPagoLineaRow : System.Data.DataRow {
            
            private v_FormaPagoLineaDataTable tablev_FormaPagoLinea;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal v_FormaPagoLineaRow(System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tablev_FormaPagoLinea = ((v_FormaPagoLineaDataTable)(this.Table));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Guid id {
                get {
                    return ((System.Guid)(this[this.tablev_FormaPagoLinea.idColumn]));
                }
                set {
                    this[this.tablev_FormaPagoLinea.idColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Guid tipoPagoID {
                get {
                    try {
                        return ((System.Guid)(this[this.tablev_FormaPagoLinea.tipoPagoIDColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'tipoPagoID\' in table \'v_FormaPagoLinea\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_FormaPagoLinea.tipoPagoIDColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Guid tipoPagoDetalleID {
                get {
                    try {
                        return ((System.Guid)(this[this.tablev_FormaPagoLinea.tipoPagoDetalleIDColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'tipoPagoDetalleID\' in table \'v_FormaPagoLinea\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_FormaPagoLinea.tipoPagoDetalleIDColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal importe {
                get {
                    return ((decimal)(this[this.tablev_FormaPagoLinea.importeColumn]));
                }
                set {
                    this[this.tablev_FormaPagoLinea.importeColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal ajuste {
                get {
                    return ((decimal)(this[this.tablev_FormaPagoLinea.ajusteColumn]));
                }
                set {
                    this[this.tablev_FormaPagoLinea.ajusteColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal pesos {
                get {
                    return ((decimal)(this[this.tablev_FormaPagoLinea.pesosColumn]));
                }
                set {
                    this[this.tablev_FormaPagoLinea.pesosColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Tipo_Pago {
                get {
                    try {
                        return ((string)(this[this.tablev_FormaPagoLinea.Tipo_PagoColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Tipo Pago\' in table \'v_FormaPagoLinea\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_FormaPagoLinea.Tipo_PagoColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string identificador {
                get {
                    try {
                        return ((string)(this[this.tablev_FormaPagoLinea.identificadorColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'identificador\' in table \'v_FormaPagoLinea\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_FormaPagoLinea.identificadorColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string operacion {
                get {
                    try {
                        return ((string)(this[this.tablev_FormaPagoLinea.operacionColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'operacion\' in table \'v_FormaPagoLinea\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_FormaPagoLinea.operacionColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string _Nro__Cheque {
                get {
                    return ((string)(this[this.tablev_FormaPagoLinea._Nro__ChequeColumn]));
                }
                set {
                    this[this.tablev_FormaPagoLinea._Nro__ChequeColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Guid bancoID {
                get {
                    try {
                        return ((System.Guid)(this[this.tablev_FormaPagoLinea.bancoIDColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'bancoID\' in table \'v_FormaPagoLinea\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_FormaPagoLinea.bancoIDColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Guid cantidadPagosID {
                get {
                    try {
                        return ((System.Guid)(this[this.tablev_FormaPagoLinea.cantidadPagosIDColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'cantidadPagosID\' in table \'v_FormaPagoLinea\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_FormaPagoLinea.cantidadPagosIDColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Guid formaPagoID {
                get {
                    return ((System.Guid)(this[this.tablev_FormaPagoLinea.formaPagoIDColumn]));
                }
                set {
                    this[this.tablev_FormaPagoLinea.formaPagoIDColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Detalle {
                get {
                    try {
                        return ((string)(this[this.tablev_FormaPagoLinea.DetalleColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Detalle\' in table \'v_FormaPagoLinea\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_FormaPagoLinea.DetalleColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Guid notaCreditoID {
                get {
                    try {
                        return ((System.Guid)(this[this.tablev_FormaPagoLinea.notaCreditoIDColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'notaCreditoID\' in table \'v_FormaPagoLinea\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_FormaPagoLinea.notaCreditoIDColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IstipoPagoIDNull() {
                return this.IsNull(this.tablev_FormaPagoLinea.tipoPagoIDColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SettipoPagoIDNull() {
                this[this.tablev_FormaPagoLinea.tipoPagoIDColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IstipoPagoDetalleIDNull() {
                return this.IsNull(this.tablev_FormaPagoLinea.tipoPagoDetalleIDColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SettipoPagoDetalleIDNull() {
                this[this.tablev_FormaPagoLinea.tipoPagoDetalleIDColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTipo_PagoNull() {
                return this.IsNull(this.tablev_FormaPagoLinea.Tipo_PagoColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTipo_PagoNull() {
                this[this.tablev_FormaPagoLinea.Tipo_PagoColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsidentificadorNull() {
                return this.IsNull(this.tablev_FormaPagoLinea.identificadorColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetidentificadorNull() {
                this[this.tablev_FormaPagoLinea.identificadorColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsoperacionNull() {
                return this.IsNull(this.tablev_FormaPagoLinea.operacionColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetoperacionNull() {
                this[this.tablev_FormaPagoLinea.operacionColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsbancoIDNull() {
                return this.IsNull(this.tablev_FormaPagoLinea.bancoIDColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetbancoIDNull() {
                this[this.tablev_FormaPagoLinea.bancoIDColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IscantidadPagosIDNull() {
                return this.IsNull(this.tablev_FormaPagoLinea.cantidadPagosIDColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetcantidadPagosIDNull() {
                this[this.tablev_FormaPagoLinea.cantidadPagosIDColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDetalleNull() {
                return this.IsNull(this.tablev_FormaPagoLinea.DetalleColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDetalleNull() {
                this[this.tablev_FormaPagoLinea.DetalleColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsnotaCreditoIDNull() {
                return this.IsNull(this.tablev_FormaPagoLinea.notaCreditoIDColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetnotaCreditoIDNull() {
                this[this.tablev_FormaPagoLinea.notaCreditoIDColumn] = System.Convert.DBNull;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class v_FormaPagoLineaRowChangeEvent : System.EventArgs {
            
            private v_FormaPagoLineaRow eventRow;
            
            private System.Data.DataRowAction eventAction;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public v_FormaPagoLineaRowChangeEvent(v_FormaPagoLineaRow row, System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public v_FormaPagoLineaRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
namespace Comunes.dsFormaPagoLineaTableAdapters {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.ComponentModel.ToolboxItem(true)]
    [System.ComponentModel.DataObjectAttribute(true)]
    [System.ComponentModel.DesignerAttribute("Microsoft.VSDesigner.DataSource.Design.TableAdapterDesigner, Microsoft.VSDesigner" +
        ", Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")]
    [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
    public partial class v_FormaPagoLineaTableAdapter : System.ComponentModel.Component {
        
        private System.Data.SqlClient.SqlDataAdapter _adapter;
        
        private System.Data.SqlClient.SqlConnection _connection;
        
        private System.Data.SqlClient.SqlCommand[] _commandCollection;
        
        private bool _clearBeforeFill;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public v_FormaPagoLineaTableAdapter() {
            this.ClearBeforeFill = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private System.Data.SqlClient.SqlDataAdapter Adapter {
            get {
                if ((this._adapter == null)) {
                    this.InitAdapter();
                }
                return this._adapter;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal System.Data.SqlClient.SqlConnection Connection {
            get {
                if ((this._connection == null)) {
                    this.InitConnection();
                }
                return this._connection;
            }
            set {
                this._connection = value;
                if ((this.Adapter.InsertCommand != null)) {
                    this.Adapter.InsertCommand.Connection = value;
                }
                if ((this.Adapter.DeleteCommand != null)) {
                    this.Adapter.DeleteCommand.Connection = value;
                }
                if ((this.Adapter.UpdateCommand != null)) {
                    this.Adapter.UpdateCommand.Connection = value;
                }
                for (int i = 0; (i < this.CommandCollection.Length); i = (i + 1)) {
                    if ((this.CommandCollection[i] != null)) {
                        ((System.Data.SqlClient.SqlCommand)(this.CommandCollection[i])).Connection = value;
                    }
                }
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected System.Data.SqlClient.SqlCommand[] CommandCollection {
            get {
                if ((this._commandCollection == null)) {
                    this.InitCommandCollection();
                }
                return this._commandCollection;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool ClearBeforeFill {
            get {
                return this._clearBeforeFill;
            }
            set {
                this._clearBeforeFill = value;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitAdapter() {
            this._adapter = new System.Data.SqlClient.SqlDataAdapter();
            System.Data.Common.DataTableMapping tableMapping = new System.Data.Common.DataTableMapping();
            tableMapping.SourceTable = "Table";
            tableMapping.DataSetTable = "v_FormaPagoLinea";
            tableMapping.ColumnMappings.Add("id", "id");
            tableMapping.ColumnMappings.Add("tipoPagoID", "tipoPagoID");
            tableMapping.ColumnMappings.Add("tipoPagoDetalleID", "tipoPagoDetalleID");
            tableMapping.ColumnMappings.Add("importe", "importe");
            tableMapping.ColumnMappings.Add("ajuste", "ajuste");
            tableMapping.ColumnMappings.Add("pesos", "pesos");
            tableMapping.ColumnMappings.Add("Tipo Pago", "Tipo Pago");
            tableMapping.ColumnMappings.Add("identificador", "identificador");
            tableMapping.ColumnMappings.Add("operacion", "operacion");
            tableMapping.ColumnMappings.Add("Nro. Cheque", "Nro. Cheque");
            tableMapping.ColumnMappings.Add("bancoID", "bancoID");
            tableMapping.ColumnMappings.Add("cantidadPagosID", "cantidadPagosID");
            tableMapping.ColumnMappings.Add("formaPagoID", "formaPagoID");
            tableMapping.ColumnMappings.Add("Detalle", "Detalle");
            tableMapping.ColumnMappings.Add("notaCreditoID", "notaCreditoID");
            this._adapter.TableMappings.Add(tableMapping);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitConnection() {
            this._connection = new System.Data.SqlClient.SqlConnection();
            this._connection.ConnectionString = global::Comunes.Properties.Settings.Default.LigierConnectionString;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitCommandCollection() {
            this._commandCollection = new System.Data.SqlClient.SqlCommand[1];
            this._commandCollection[0] = new System.Data.SqlClient.SqlCommand();
            this._commandCollection[0].Connection = this.Connection;
            this._commandCollection[0].CommandText = "SELECT id, tipoPagoID, tipoPagoDetalleID, importe, ajuste, pesos, [Tipo Pago], id" +
                "entificador, operacion, [Nro. Cheque], bancoID, cantidadPagosID, formaPagoID, De" +
                "talle, notaCreditoID FROM dbo.v_FormaPagoLinea";
            this._commandCollection[0].CommandType = System.Data.CommandType.Text;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Fill, true)]
        public virtual int Fill(dsFormaPagoLinea.v_FormaPagoLineaDataTable dataTable) {
            this.Adapter.SelectCommand = this.CommandCollection[0];
            if ((this.ClearBeforeFill == true)) {
                dataTable.Clear();
            }
            int returnValue = this.Adapter.Fill(dataTable);
            return returnValue;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public virtual dsFormaPagoLinea.v_FormaPagoLineaDataTable GetData() {
            this.Adapter.SelectCommand = this.CommandCollection[0];
            dsFormaPagoLinea.v_FormaPagoLineaDataTable dataTable = new dsFormaPagoLinea.v_FormaPagoLineaDataTable();
            this.Adapter.Fill(dataTable);
            return dataTable;
        }
    }
}

#pragma warning restore 1591