//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Comunes {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.ComponentModel.ToolboxItem(true)]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [System.Xml.Serialization.XmlRootAttribute("dsListadoFacturas")]
    [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dsListadoFacturas : System.Data.DataSet {
        
        private v_FacturaDataTable tablev_Factura;
        
        private System.Data.SchemaSerializationMode _schemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public dsListadoFacturas() {
            this.BeginInit();
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected dsListadoFacturas(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == System.Data.SchemaSerializationMode.IncludeSchema)) {
                System.Data.DataSet ds = new System.Data.DataSet();
                ds.ReadXmlSchema(new System.Xml.XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["v_Factura"] != null)) {
                    base.Tables.Add(new v_FacturaDataTable(ds.Tables["v_Factura"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new System.Xml.XmlTextReader(new System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public v_FacturaDataTable v_Factura {
            get {
                return this.tablev_Factura;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.BrowsableAttribute(true)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override System.Data.DataSet Clone() {
            dsListadoFacturas cln = ((dsListadoFacturas)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                System.Data.DataSet ds = new System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["v_Factura"] != null)) {
                    base.Tables.Add(new v_FacturaDataTable(ds.Tables["v_Factura"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new System.Xml.XmlTextReader(stream), null);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tablev_Factura = ((v_FacturaDataTable)(base.Tables["v_Factura"]));
            if ((initTable == true)) {
                if ((this.tablev_Factura != null)) {
                    this.tablev_Factura.InitVars();
                }
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "dsListadoFacturas";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsListadoFacturas.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            this.tablev_Factura = new v_FacturaDataTable();
            base.Tables.Add(this.tablev_Factura);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializev_Factura() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(System.Xml.Schema.XmlSchemaSet xs) {
            dsListadoFacturas ds = new dsListadoFacturas();
            System.Xml.Schema.XmlSchemaComplexType type = new System.Xml.Schema.XmlSchemaComplexType();
            System.Xml.Schema.XmlSchemaSequence sequence = new System.Xml.Schema.XmlSchemaSequence();
            xs.Add(ds.GetSchemaSerializable());
            System.Xml.Schema.XmlSchemaAny any = new System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            return type;
        }
        
        public delegate void v_FacturaRowChangeEventHandler(object sender, v_FacturaRowChangeEvent e);
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [System.Serializable()]
        [System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class v_FacturaDataTable : System.Data.DataTable, System.Collections.IEnumerable {
            
            private System.Data.DataColumn columnFecha;
            
            private System.Data.DataColumn columnclienteID;
            
            private System.Data.DataColumn columnapellido;
            
            private System.Data.DataColumn columnnombres;
            
            private System.Data.DataColumn columnRazón_Social;
            
            private System.Data.DataColumn columnivaIDCliente;
            
            private System.Data.DataColumn columnIVA;
            
            private System.Data.DataColumn columnDirección_Cliente;
            
            private System.Data.DataColumn columnCUIT;
            
            private System.Data.DataColumn columnid;
            
            private System.Data.DataColumn columnDirección_Entrega;
            
            private System.Data.DataColumn columnvendedorID;
            
            private System.Data.DataColumn columnVendedor;
            
            private System.Data.DataColumn columnautorizadorBonificacionID;
            
            private System.Data.DataColumn columnAutorizó;
            
            private System.Data.DataColumn columnCondición_de_Entrega;
            
            private System.Data.DataColumn columncondicionEntregaID;
            
            private System.Data.DataColumn column_Bonif___;
            
            private System.Data.DataColumn columnSubTotal_1;
            
            private System.Data.DataColumn columnIVA_1;
            
            private System.Data.DataColumn columnIVA_2;
            
            private System.Data.DataColumn columntotal;
            
            private System.Data.DataColumn columnestadoFacturaID;
            
            private System.Data.DataColumn columnmaquinaID;
            
            private System.Data.DataColumn columnMáquina;
            
            private System.Data.DataColumn columnSubTotal_2;
            
            private System.Data.DataColumn column_Bonif__Importe;
            
            private System.Data.DataColumn columnformaPagoID;
            
            private System.Data.DataColumn columnfacturaSuc;
            
            private System.Data.DataColumn columnfacturaNro;
            
            private System.Data.DataColumn columnTipo_Factura;
            
            private System.Data.DataColumn column_Nro__Factura;
            
            private System.Data.DataColumn columnjornadaVentaID;
            
            private System.Data.DataColumn columnsucursalID;
            
            private System.Data.DataColumn columnSucursal;
            
            private System.Data.DataColumn columnnotaPedidoID;
            
            private System.Data.DataColumn columnEstado;
            
            private System.Data.DataColumn columnestadoCuentaCorrienteID;
            
            private System.Data.DataColumn column_Estado_Cta__Cte_;
            
            private System.Data.DataColumn columnPlazo_Pago;
            
            private System.Data.DataColumn column_Ejercicio_Nro_;
            
            private System.Data.DataColumn columnnotaPedidoSuc;
            
            private System.Data.DataColumn columnnotaPedidoNro;
            
            private System.Data.DataColumn columnNota_Pedido;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public v_FacturaDataTable() {
                this.TableName = "v_Factura";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal v_FacturaDataTable(System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected v_FacturaDataTable(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn FechaColumn {
                get {
                    return this.columnFecha;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn clienteIDColumn {
                get {
                    return this.columnclienteID;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn apellidoColumn {
                get {
                    return this.columnapellido;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn nombresColumn {
                get {
                    return this.columnnombres;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Razón_SocialColumn {
                get {
                    return this.columnRazón_Social;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn ivaIDClienteColumn {
                get {
                    return this.columnivaIDCliente;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn IVAColumn {
                get {
                    return this.columnIVA;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Dirección_ClienteColumn {
                get {
                    return this.columnDirección_Cliente;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn CUITColumn {
                get {
                    return this.columnCUIT;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn idColumn {
                get {
                    return this.columnid;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Dirección_EntregaColumn {
                get {
                    return this.columnDirección_Entrega;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn vendedorIDColumn {
                get {
                    return this.columnvendedorID;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn VendedorColumn {
                get {
                    return this.columnVendedor;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn autorizadorBonificacionIDColumn {
                get {
                    return this.columnautorizadorBonificacionID;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn AutorizóColumn {
                get {
                    return this.columnAutorizó;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Condición_de_EntregaColumn {
                get {
                    return this.columnCondición_de_Entrega;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn condicionEntregaIDColumn {
                get {
                    return this.columncondicionEntregaID;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn _Bonif___Column {
                get {
                    return this.column_Bonif___;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn SubTotal_1Column {
                get {
                    return this.columnSubTotal_1;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn IVA_1Column {
                get {
                    return this.columnIVA_1;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn IVA_2Column {
                get {
                    return this.columnIVA_2;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn totalColumn {
                get {
                    return this.columntotal;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn estadoFacturaIDColumn {
                get {
                    return this.columnestadoFacturaID;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn maquinaIDColumn {
                get {
                    return this.columnmaquinaID;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn MáquinaColumn {
                get {
                    return this.columnMáquina;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn SubTotal_2Column {
                get {
                    return this.columnSubTotal_2;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn _Bonif__ImporteColumn {
                get {
                    return this.column_Bonif__Importe;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn formaPagoIDColumn {
                get {
                    return this.columnformaPagoID;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn facturaSucColumn {
                get {
                    return this.columnfacturaSuc;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn facturaNroColumn {
                get {
                    return this.columnfacturaNro;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Tipo_FacturaColumn {
                get {
                    return this.columnTipo_Factura;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn _Nro__FacturaColumn {
                get {
                    return this.column_Nro__Factura;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn jornadaVentaIDColumn {
                get {
                    return this.columnjornadaVentaID;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn sucursalIDColumn {
                get {
                    return this.columnsucursalID;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn SucursalColumn {
                get {
                    return this.columnSucursal;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn notaPedidoIDColumn {
                get {
                    return this.columnnotaPedidoID;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn EstadoColumn {
                get {
                    return this.columnEstado;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn estadoCuentaCorrienteIDColumn {
                get {
                    return this.columnestadoCuentaCorrienteID;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn _Estado_Cta__Cte_Column {
                get {
                    return this.column_Estado_Cta__Cte_;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Plazo_PagoColumn {
                get {
                    return this.columnPlazo_Pago;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn _Ejercicio_Nro_Column {
                get {
                    return this.column_Ejercicio_Nro_;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn notaPedidoSucColumn {
                get {
                    return this.columnnotaPedidoSuc;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn notaPedidoNroColumn {
                get {
                    return this.columnnotaPedidoNro;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Nota_PedidoColumn {
                get {
                    return this.columnNota_Pedido;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public v_FacturaRow this[int index] {
                get {
                    return ((v_FacturaRow)(this.Rows[index]));
                }
            }
            
            public event v_FacturaRowChangeEventHandler v_FacturaRowChanging;
            
            public event v_FacturaRowChangeEventHandler v_FacturaRowChanged;
            
            public event v_FacturaRowChangeEventHandler v_FacturaRowDeleting;
            
            public event v_FacturaRowChangeEventHandler v_FacturaRowDeleted;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Addv_FacturaRow(v_FacturaRow row) {
                this.Rows.Add(row);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public v_FacturaRow Addv_FacturaRow(
                        System.DateTime Fecha, 
                        System.Guid clienteID, 
                        string apellido, 
                        string nombres, 
                        string Razón_Social, 
                        System.Guid ivaIDCliente, 
                        string IVA, 
                        string Dirección_Cliente, 
                        string CUIT, 
                        System.Guid id, 
                        string Dirección_Entrega, 
                        System.Guid vendedorID, 
                        string Vendedor, 
                        System.Guid autorizadorBonificacionID, 
                        string Autorizó, 
                        string Condición_de_Entrega, 
                        System.Guid condicionEntregaID, 
                        decimal _Bonif___, 
                        decimal SubTotal_1, 
                        decimal IVA_1, 
                        decimal IVA_2, 
                        decimal total, 
                        System.Guid estadoFacturaID, 
                        System.Guid maquinaID, 
                        string Máquina, 
                        decimal SubTotal_2, 
                        decimal _Bonif__Importe, 
                        System.Guid formaPagoID, 
                        string facturaSuc, 
                        string facturaNro, 
                        string Tipo_Factura, 
                        string _Nro__Factura, 
                        System.Guid jornadaVentaID, 
                        System.Guid sucursalID, 
                        string Sucursal, 
                        System.Guid notaPedidoID, 
                        string Estado, 
                        System.Guid estadoCuentaCorrienteID, 
                        string _Estado_Cta__Cte_, 
                        string Plazo_Pago, 
                        int _Ejercicio_Nro_, 
                        string notaPedidoSuc, 
                        string notaPedidoNro, 
                        string Nota_Pedido) {
                v_FacturaRow rowv_FacturaRow = ((v_FacturaRow)(this.NewRow()));
                rowv_FacturaRow.ItemArray = new object[] {
                        Fecha,
                        clienteID,
                        apellido,
                        nombres,
                        Razón_Social,
                        ivaIDCliente,
                        IVA,
                        Dirección_Cliente,
                        CUIT,
                        id,
                        Dirección_Entrega,
                        vendedorID,
                        Vendedor,
                        autorizadorBonificacionID,
                        Autorizó,
                        Condición_de_Entrega,
                        condicionEntregaID,
                        _Bonif___,
                        SubTotal_1,
                        IVA_1,
                        IVA_2,
                        total,
                        estadoFacturaID,
                        maquinaID,
                        Máquina,
                        SubTotal_2,
                        _Bonif__Importe,
                        formaPagoID,
                        facturaSuc,
                        facturaNro,
                        Tipo_Factura,
                        _Nro__Factura,
                        jornadaVentaID,
                        sucursalID,
                        Sucursal,
                        notaPedidoID,
                        Estado,
                        estadoCuentaCorrienteID,
                        _Estado_Cta__Cte_,
                        Plazo_Pago,
                        _Ejercicio_Nro_,
                        notaPedidoSuc,
                        notaPedidoNro,
                        Nota_Pedido};
                this.Rows.Add(rowv_FacturaRow);
                return rowv_FacturaRow;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public virtual System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override System.Data.DataTable Clone() {
                v_FacturaDataTable cln = ((v_FacturaDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Data.DataTable CreateInstance() {
                return new v_FacturaDataTable();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnFecha = base.Columns["Fecha"];
                this.columnclienteID = base.Columns["clienteID"];
                this.columnapellido = base.Columns["apellido"];
                this.columnnombres = base.Columns["nombres"];
                this.columnRazón_Social = base.Columns["Razón Social"];
                this.columnivaIDCliente = base.Columns["ivaIDCliente"];
                this.columnIVA = base.Columns["IVA"];
                this.columnDirección_Cliente = base.Columns["Dirección Cliente"];
                this.columnCUIT = base.Columns["CUIT"];
                this.columnid = base.Columns["id"];
                this.columnDirección_Entrega = base.Columns["Dirección Entrega"];
                this.columnvendedorID = base.Columns["vendedorID"];
                this.columnVendedor = base.Columns["Vendedor"];
                this.columnautorizadorBonificacionID = base.Columns["autorizadorBonificacionID"];
                this.columnAutorizó = base.Columns["Autorizó"];
                this.columnCondición_de_Entrega = base.Columns["Condición de Entrega"];
                this.columncondicionEntregaID = base.Columns["condicionEntregaID"];
                this.column_Bonif___ = base.Columns["Bonif. %"];
                this.columnSubTotal_1 = base.Columns["SubTotal 1"];
                this.columnIVA_1 = base.Columns["IVA 1"];
                this.columnIVA_2 = base.Columns["IVA 2"];
                this.columntotal = base.Columns["total"];
                this.columnestadoFacturaID = base.Columns["estadoFacturaID"];
                this.columnmaquinaID = base.Columns["maquinaID"];
                this.columnMáquina = base.Columns["Máquina"];
                this.columnSubTotal_2 = base.Columns["SubTotal 2"];
                this.column_Bonif__Importe = base.Columns["Bonif. Importe"];
                this.columnformaPagoID = base.Columns["formaPagoID"];
                this.columnfacturaSuc = base.Columns["facturaSuc"];
                this.columnfacturaNro = base.Columns["facturaNro"];
                this.columnTipo_Factura = base.Columns["Tipo Factura"];
                this.column_Nro__Factura = base.Columns["Nro. Factura"];
                this.columnjornadaVentaID = base.Columns["jornadaVentaID"];
                this.columnsucursalID = base.Columns["sucursalID"];
                this.columnSucursal = base.Columns["Sucursal"];
                this.columnnotaPedidoID = base.Columns["notaPedidoID"];
                this.columnEstado = base.Columns["Estado"];
                this.columnestadoCuentaCorrienteID = base.Columns["estadoCuentaCorrienteID"];
                this.column_Estado_Cta__Cte_ = base.Columns["Estado Cta. Cte."];
                this.columnPlazo_Pago = base.Columns["Plazo Pago"];
                this.column_Ejercicio_Nro_ = base.Columns["Ejercicio Nro."];
                this.columnnotaPedidoSuc = base.Columns["notaPedidoSuc"];
                this.columnnotaPedidoNro = base.Columns["notaPedidoNro"];
                this.columnNota_Pedido = base.Columns["Nota Pedido"];
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnFecha = new System.Data.DataColumn("Fecha", typeof(System.DateTime), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnFecha);
                this.columnclienteID = new System.Data.DataColumn("clienteID", typeof(System.Guid), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnclienteID);
                this.columnapellido = new System.Data.DataColumn("apellido", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnapellido);
                this.columnnombres = new System.Data.DataColumn("nombres", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnnombres);
                this.columnRazón_Social = new System.Data.DataColumn("Razón Social", typeof(string), null, System.Data.MappingType.Element);
                this.columnRazón_Social.ExtendedProperties.Add("Generator_ColumnPropNameInRow", "Razón_Social");
                this.columnRazón_Social.ExtendedProperties.Add("Generator_ColumnPropNameInTable", "Razón_SocialColumn");
                this.columnRazón_Social.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "columnRazón_Social");
                this.columnRazón_Social.ExtendedProperties.Add("Generator_UserColumnName", "Razón Social");
                base.Columns.Add(this.columnRazón_Social);
                this.columnivaIDCliente = new System.Data.DataColumn("ivaIDCliente", typeof(System.Guid), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnivaIDCliente);
                this.columnIVA = new System.Data.DataColumn("IVA", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnIVA);
                this.columnDirección_Cliente = new System.Data.DataColumn("Dirección Cliente", typeof(string), null, System.Data.MappingType.Element);
                this.columnDirección_Cliente.ExtendedProperties.Add("Generator_ColumnPropNameInRow", "Dirección_Cliente");
                this.columnDirección_Cliente.ExtendedProperties.Add("Generator_ColumnPropNameInTable", "Dirección_ClienteColumn");
                this.columnDirección_Cliente.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "columnDirección_Cliente");
                this.columnDirección_Cliente.ExtendedProperties.Add("Generator_UserColumnName", "Dirección Cliente");
                base.Columns.Add(this.columnDirección_Cliente);
                this.columnCUIT = new System.Data.DataColumn("CUIT", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnCUIT);
                this.columnid = new System.Data.DataColumn("id", typeof(System.Guid), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnid);
                this.columnDirección_Entrega = new System.Data.DataColumn("Dirección Entrega", typeof(string), null, System.Data.MappingType.Element);
                this.columnDirección_Entrega.ExtendedProperties.Add("Generator_ColumnPropNameInRow", "Dirección_Entrega");
                this.columnDirección_Entrega.ExtendedProperties.Add("Generator_ColumnPropNameInTable", "Dirección_EntregaColumn");
                this.columnDirección_Entrega.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "columnDirección_Entrega");
                this.columnDirección_Entrega.ExtendedProperties.Add("Generator_UserColumnName", "Dirección Entrega");
                base.Columns.Add(this.columnDirección_Entrega);
                this.columnvendedorID = new System.Data.DataColumn("vendedorID", typeof(System.Guid), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnvendedorID);
                this.columnVendedor = new System.Data.DataColumn("Vendedor", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnVendedor);
                this.columnautorizadorBonificacionID = new System.Data.DataColumn("autorizadorBonificacionID", typeof(System.Guid), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnautorizadorBonificacionID);
                this.columnAutorizó = new System.Data.DataColumn("Autorizó", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnAutorizó);
                this.columnCondición_de_Entrega = new System.Data.DataColumn("Condición de Entrega", typeof(string), null, System.Data.MappingType.Element);
                this.columnCondición_de_Entrega.ExtendedProperties.Add("Generator_ColumnPropNameInRow", "Condición_de_Entrega");
                this.columnCondición_de_Entrega.ExtendedProperties.Add("Generator_ColumnPropNameInTable", "Condición_de_EntregaColumn");
                this.columnCondición_de_Entrega.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "columnCondición_de_Entrega");
                this.columnCondición_de_Entrega.ExtendedProperties.Add("Generator_UserColumnName", "Condición de Entrega");
                base.Columns.Add(this.columnCondición_de_Entrega);
                this.columncondicionEntregaID = new System.Data.DataColumn("condicionEntregaID", typeof(System.Guid), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columncondicionEntregaID);
                this.column_Bonif___ = new System.Data.DataColumn("Bonif. %", typeof(decimal), null, System.Data.MappingType.Element);
                this.column_Bonif___.ExtendedProperties.Add("Generator_ColumnPropNameInRow", "_Bonif___");
                this.column_Bonif___.ExtendedProperties.Add("Generator_ColumnPropNameInTable", "_Bonif___Column");
                this.column_Bonif___.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "column_Bonif___");
                this.column_Bonif___.ExtendedProperties.Add("Generator_UserColumnName", "Bonif. %");
                base.Columns.Add(this.column_Bonif___);
                this.columnSubTotal_1 = new System.Data.DataColumn("SubTotal 1", typeof(decimal), null, System.Data.MappingType.Element);
                this.columnSubTotal_1.ExtendedProperties.Add("Generator_ColumnPropNameInRow", "SubTotal_1");
                this.columnSubTotal_1.ExtendedProperties.Add("Generator_ColumnPropNameInTable", "SubTotal_1Column");
                this.columnSubTotal_1.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "columnSubTotal_1");
                this.columnSubTotal_1.ExtendedProperties.Add("Generator_UserColumnName", "SubTotal 1");
                base.Columns.Add(this.columnSubTotal_1);
                this.columnIVA_1 = new System.Data.DataColumn("IVA 1", typeof(decimal), null, System.Data.MappingType.Element);
                this.columnIVA_1.ExtendedProperties.Add("Generator_ColumnPropNameInRow", "IVA_1");
                this.columnIVA_1.ExtendedProperties.Add("Generator_ColumnPropNameInTable", "IVA_1Column");
                this.columnIVA_1.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "columnIVA_1");
                this.columnIVA_1.ExtendedProperties.Add("Generator_UserColumnName", "IVA 1");
                base.Columns.Add(this.columnIVA_1);
                this.columnIVA_2 = new System.Data.DataColumn("IVA 2", typeof(decimal), null, System.Data.MappingType.Element);
                this.columnIVA_2.ExtendedProperties.Add("Generator_ColumnPropNameInRow", "IVA_2");
                this.columnIVA_2.ExtendedProperties.Add("Generator_ColumnPropNameInTable", "IVA_2Column");
                this.columnIVA_2.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "columnIVA_2");
                this.columnIVA_2.ExtendedProperties.Add("Generator_UserColumnName", "IVA 2");
                base.Columns.Add(this.columnIVA_2);
                this.columntotal = new System.Data.DataColumn("total", typeof(decimal), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columntotal);
                this.columnestadoFacturaID = new System.Data.DataColumn("estadoFacturaID", typeof(System.Guid), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnestadoFacturaID);
                this.columnmaquinaID = new System.Data.DataColumn("maquinaID", typeof(System.Guid), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnmaquinaID);
                this.columnMáquina = new System.Data.DataColumn("Máquina", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnMáquina);
                this.columnSubTotal_2 = new System.Data.DataColumn("SubTotal 2", typeof(decimal), null, System.Data.MappingType.Element);
                this.columnSubTotal_2.ExtendedProperties.Add("Generator_ColumnPropNameInRow", "SubTotal_2");
                this.columnSubTotal_2.ExtendedProperties.Add("Generator_ColumnPropNameInTable", "SubTotal_2Column");
                this.columnSubTotal_2.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "columnSubTotal_2");
                this.columnSubTotal_2.ExtendedProperties.Add("Generator_UserColumnName", "SubTotal 2");
                base.Columns.Add(this.columnSubTotal_2);
                this.column_Bonif__Importe = new System.Data.DataColumn("Bonif. Importe", typeof(decimal), null, System.Data.MappingType.Element);
                this.column_Bonif__Importe.ExtendedProperties.Add("Generator_ColumnPropNameInRow", "_Bonif__Importe");
                this.column_Bonif__Importe.ExtendedProperties.Add("Generator_ColumnPropNameInTable", "_Bonif__ImporteColumn");
                this.column_Bonif__Importe.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "column_Bonif__Importe");
                this.column_Bonif__Importe.ExtendedProperties.Add("Generator_UserColumnName", "Bonif. Importe");
                base.Columns.Add(this.column_Bonif__Importe);
                this.columnformaPagoID = new System.Data.DataColumn("formaPagoID", typeof(System.Guid), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnformaPagoID);
                this.columnfacturaSuc = new System.Data.DataColumn("facturaSuc", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnfacturaSuc);
                this.columnfacturaNro = new System.Data.DataColumn("facturaNro", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnfacturaNro);
                this.columnTipo_Factura = new System.Data.DataColumn("Tipo Factura", typeof(string), null, System.Data.MappingType.Element);
                this.columnTipo_Factura.ExtendedProperties.Add("Generator_ColumnPropNameInRow", "Tipo_Factura");
                this.columnTipo_Factura.ExtendedProperties.Add("Generator_ColumnPropNameInTable", "Tipo_FacturaColumn");
                this.columnTipo_Factura.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "columnTipo_Factura");
                this.columnTipo_Factura.ExtendedProperties.Add("Generator_UserColumnName", "Tipo Factura");
                base.Columns.Add(this.columnTipo_Factura);
                this.column_Nro__Factura = new System.Data.DataColumn("Nro. Factura", typeof(string), null, System.Data.MappingType.Element);
                this.column_Nro__Factura.ExtendedProperties.Add("Generator_ColumnPropNameInRow", "_Nro__Factura");
                this.column_Nro__Factura.ExtendedProperties.Add("Generator_ColumnPropNameInTable", "_Nro__FacturaColumn");
                this.column_Nro__Factura.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "column_Nro__Factura");
                this.column_Nro__Factura.ExtendedProperties.Add("Generator_UserColumnName", "Nro. Factura");
                base.Columns.Add(this.column_Nro__Factura);
                this.columnjornadaVentaID = new System.Data.DataColumn("jornadaVentaID", typeof(System.Guid), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnjornadaVentaID);
                this.columnsucursalID = new System.Data.DataColumn("sucursalID", typeof(System.Guid), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnsucursalID);
                this.columnSucursal = new System.Data.DataColumn("Sucursal", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnSucursal);
                this.columnnotaPedidoID = new System.Data.DataColumn("notaPedidoID", typeof(System.Guid), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnnotaPedidoID);
                this.columnEstado = new System.Data.DataColumn("Estado", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnEstado);
                this.columnestadoCuentaCorrienteID = new System.Data.DataColumn("estadoCuentaCorrienteID", typeof(System.Guid), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnestadoCuentaCorrienteID);
                this.column_Estado_Cta__Cte_ = new System.Data.DataColumn("Estado Cta. Cte.", typeof(string), null, System.Data.MappingType.Element);
                this.column_Estado_Cta__Cte_.ExtendedProperties.Add("Generator_ColumnPropNameInRow", "_Estado_Cta__Cte_");
                this.column_Estado_Cta__Cte_.ExtendedProperties.Add("Generator_ColumnPropNameInTable", "_Estado_Cta__Cte_Column");
                this.column_Estado_Cta__Cte_.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "column_Estado_Cta__Cte_");
                this.column_Estado_Cta__Cte_.ExtendedProperties.Add("Generator_UserColumnName", "Estado Cta. Cte.");
                base.Columns.Add(this.column_Estado_Cta__Cte_);
                this.columnPlazo_Pago = new System.Data.DataColumn("Plazo Pago", typeof(string), null, System.Data.MappingType.Element);
                this.columnPlazo_Pago.ExtendedProperties.Add("Generator_ColumnPropNameInRow", "Plazo_Pago");
                this.columnPlazo_Pago.ExtendedProperties.Add("Generator_ColumnPropNameInTable", "Plazo_PagoColumn");
                this.columnPlazo_Pago.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "columnPlazo_Pago");
                this.columnPlazo_Pago.ExtendedProperties.Add("Generator_UserColumnName", "Plazo Pago");
                base.Columns.Add(this.columnPlazo_Pago);
                this.column_Ejercicio_Nro_ = new System.Data.DataColumn("Ejercicio Nro.", typeof(int), null, System.Data.MappingType.Element);
                this.column_Ejercicio_Nro_.ExtendedProperties.Add("Generator_ColumnPropNameInRow", "_Ejercicio_Nro_");
                this.column_Ejercicio_Nro_.ExtendedProperties.Add("Generator_ColumnPropNameInTable", "_Ejercicio_Nro_Column");
                this.column_Ejercicio_Nro_.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "column_Ejercicio_Nro_");
                this.column_Ejercicio_Nro_.ExtendedProperties.Add("Generator_UserColumnName", "Ejercicio Nro.");
                base.Columns.Add(this.column_Ejercicio_Nro_);
                this.columnnotaPedidoSuc = new System.Data.DataColumn("notaPedidoSuc", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnnotaPedidoSuc);
                this.columnnotaPedidoNro = new System.Data.DataColumn("notaPedidoNro", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnnotaPedidoNro);
                this.columnNota_Pedido = new System.Data.DataColumn("Nota Pedido", typeof(string), null, System.Data.MappingType.Element);
                this.columnNota_Pedido.ExtendedProperties.Add("Generator_ColumnPropNameInRow", "Nota_Pedido");
                this.columnNota_Pedido.ExtendedProperties.Add("Generator_ColumnPropNameInTable", "Nota_PedidoColumn");
                this.columnNota_Pedido.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "columnNota_Pedido");
                this.columnNota_Pedido.ExtendedProperties.Add("Generator_UserColumnName", "Nota Pedido");
                base.Columns.Add(this.columnNota_Pedido);
                this.columnFecha.AllowDBNull = false;
                this.columnRazón_Social.AllowDBNull = false;
                this.columnDirección_Cliente.AllowDBNull = false;
                this.columnCUIT.AllowDBNull = false;
                this.columnid.AllowDBNull = false;
                this.columnDirección_Entrega.AllowDBNull = false;
                this.columnVendedor.ReadOnly = true;
                this.columnAutorizó.ReadOnly = true;
                this.column_Bonif___.AllowDBNull = false;
                this.columnSubTotal_1.AllowDBNull = false;
                this.columnIVA_1.AllowDBNull = false;
                this.columnIVA_2.AllowDBNull = false;
                this.columntotal.AllowDBNull = false;
                this.columnSubTotal_2.AllowDBNull = false;
                this.column_Bonif__Importe.AllowDBNull = false;
                this.columnfacturaSuc.AllowDBNull = false;
                this.columnfacturaNro.AllowDBNull = false;
                this.columnTipo_Factura.AllowDBNull = false;
                this.column_Nro__Factura.ReadOnly = true;
                this.columnSucursal.ReadOnly = true;
                this.columnNota_Pedido.ReadOnly = true;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public v_FacturaRow Newv_FacturaRow() {
                return ((v_FacturaRow)(this.NewRow()));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Data.DataRow NewRowFromBuilder(System.Data.DataRowBuilder builder) {
                return new v_FacturaRow(builder);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Type GetRowType() {
                return typeof(v_FacturaRow);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.v_FacturaRowChanged != null)) {
                    this.v_FacturaRowChanged(this, new v_FacturaRowChangeEvent(((v_FacturaRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.v_FacturaRowChanging != null)) {
                    this.v_FacturaRowChanging(this, new v_FacturaRowChangeEvent(((v_FacturaRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.v_FacturaRowDeleted != null)) {
                    this.v_FacturaRowDeleted(this, new v_FacturaRowChangeEvent(((v_FacturaRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.v_FacturaRowDeleting != null)) {
                    this.v_FacturaRowDeleting(this, new v_FacturaRowChangeEvent(((v_FacturaRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Removev_FacturaRow(v_FacturaRow row) {
                this.Rows.Remove(row);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(System.Xml.Schema.XmlSchemaSet xs) {
                System.Xml.Schema.XmlSchemaComplexType type = new System.Xml.Schema.XmlSchemaComplexType();
                System.Xml.Schema.XmlSchemaSequence sequence = new System.Xml.Schema.XmlSchemaSequence();
                dsListadoFacturas ds = new dsListadoFacturas();
                xs.Add(ds.GetSchemaSerializable());
                System.Xml.Schema.XmlSchemaAny any1 = new System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                System.Xml.Schema.XmlSchemaAny any2 = new System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                System.Xml.Schema.XmlSchemaAttribute attribute1 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                System.Xml.Schema.XmlSchemaAttribute attribute2 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "v_FacturaDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                return type;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class v_FacturaRow : System.Data.DataRow {
            
            private v_FacturaDataTable tablev_Factura;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal v_FacturaRow(System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tablev_Factura = ((v_FacturaDataTable)(this.Table));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime Fecha {
                get {
                    return ((System.DateTime)(this[this.tablev_Factura.FechaColumn]));
                }
                set {
                    this[this.tablev_Factura.FechaColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Guid clienteID {
                get {
                    try {
                        return ((System.Guid)(this[this.tablev_Factura.clienteIDColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'clienteID\' in table \'v_Factura\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Factura.clienteIDColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string apellido {
                get {
                    try {
                        return ((string)(this[this.tablev_Factura.apellidoColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'apellido\' in table \'v_Factura\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Factura.apellidoColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string nombres {
                get {
                    try {
                        return ((string)(this[this.tablev_Factura.nombresColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'nombres\' in table \'v_Factura\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Factura.nombresColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Razón_Social {
                get {
                    return ((string)(this[this.tablev_Factura.Razón_SocialColumn]));
                }
                set {
                    this[this.tablev_Factura.Razón_SocialColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Guid ivaIDCliente {
                get {
                    try {
                        return ((System.Guid)(this[this.tablev_Factura.ivaIDClienteColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'ivaIDCliente\' in table \'v_Factura\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Factura.ivaIDClienteColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string IVA {
                get {
                    try {
                        return ((string)(this[this.tablev_Factura.IVAColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'IVA\' in table \'v_Factura\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Factura.IVAColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Dirección_Cliente {
                get {
                    return ((string)(this[this.tablev_Factura.Dirección_ClienteColumn]));
                }
                set {
                    this[this.tablev_Factura.Dirección_ClienteColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CUIT {
                get {
                    return ((string)(this[this.tablev_Factura.CUITColumn]));
                }
                set {
                    this[this.tablev_Factura.CUITColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Guid id {
                get {
                    return ((System.Guid)(this[this.tablev_Factura.idColumn]));
                }
                set {
                    this[this.tablev_Factura.idColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Dirección_Entrega {
                get {
                    return ((string)(this[this.tablev_Factura.Dirección_EntregaColumn]));
                }
                set {
                    this[this.tablev_Factura.Dirección_EntregaColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Guid vendedorID {
                get {
                    try {
                        return ((System.Guid)(this[this.tablev_Factura.vendedorIDColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'vendedorID\' in table \'v_Factura\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Factura.vendedorIDColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Vendedor {
                get {
                    try {
                        return ((string)(this[this.tablev_Factura.VendedorColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Vendedor\' in table \'v_Factura\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Factura.VendedorColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Guid autorizadorBonificacionID {
                get {
                    try {
                        return ((System.Guid)(this[this.tablev_Factura.autorizadorBonificacionIDColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'autorizadorBonificacionID\' in table \'v_Factura\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Factura.autorizadorBonificacionIDColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Autorizó {
                get {
                    try {
                        return ((string)(this[this.tablev_Factura.AutorizóColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Autorizó\' in table \'v_Factura\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Factura.AutorizóColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Condición_de_Entrega {
                get {
                    try {
                        return ((string)(this[this.tablev_Factura.Condición_de_EntregaColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Condición de Entrega\' in table \'v_Factura\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Factura.Condición_de_EntregaColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Guid condicionEntregaID {
                get {
                    try {
                        return ((System.Guid)(this[this.tablev_Factura.condicionEntregaIDColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'condicionEntregaID\' in table \'v_Factura\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Factura.condicionEntregaIDColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal _Bonif___ {
                get {
                    return ((decimal)(this[this.tablev_Factura._Bonif___Column]));
                }
                set {
                    this[this.tablev_Factura._Bonif___Column] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal SubTotal_1 {
                get {
                    return ((decimal)(this[this.tablev_Factura.SubTotal_1Column]));
                }
                set {
                    this[this.tablev_Factura.SubTotal_1Column] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal IVA_1 {
                get {
                    return ((decimal)(this[this.tablev_Factura.IVA_1Column]));
                }
                set {
                    this[this.tablev_Factura.IVA_1Column] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal IVA_2 {
                get {
                    return ((decimal)(this[this.tablev_Factura.IVA_2Column]));
                }
                set {
                    this[this.tablev_Factura.IVA_2Column] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal total {
                get {
                    return ((decimal)(this[this.tablev_Factura.totalColumn]));
                }
                set {
                    this[this.tablev_Factura.totalColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Guid estadoFacturaID {
                get {
                    try {
                        return ((System.Guid)(this[this.tablev_Factura.estadoFacturaIDColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'estadoFacturaID\' in table \'v_Factura\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Factura.estadoFacturaIDColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Guid maquinaID {
                get {
                    try {
                        return ((System.Guid)(this[this.tablev_Factura.maquinaIDColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'maquinaID\' in table \'v_Factura\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Factura.maquinaIDColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Máquina {
                get {
                    try {
                        return ((string)(this[this.tablev_Factura.MáquinaColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Máquina\' in table \'v_Factura\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Factura.MáquinaColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal SubTotal_2 {
                get {
                    return ((decimal)(this[this.tablev_Factura.SubTotal_2Column]));
                }
                set {
                    this[this.tablev_Factura.SubTotal_2Column] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal _Bonif__Importe {
                get {
                    return ((decimal)(this[this.tablev_Factura._Bonif__ImporteColumn]));
                }
                set {
                    this[this.tablev_Factura._Bonif__ImporteColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Guid formaPagoID {
                get {
                    try {
                        return ((System.Guid)(this[this.tablev_Factura.formaPagoIDColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'formaPagoID\' in table \'v_Factura\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Factura.formaPagoIDColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string facturaSuc {
                get {
                    return ((string)(this[this.tablev_Factura.facturaSucColumn]));
                }
                set {
                    this[this.tablev_Factura.facturaSucColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string facturaNro {
                get {
                    return ((string)(this[this.tablev_Factura.facturaNroColumn]));
                }
                set {
                    this[this.tablev_Factura.facturaNroColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Tipo_Factura {
                get {
                    return ((string)(this[this.tablev_Factura.Tipo_FacturaColumn]));
                }
                set {
                    this[this.tablev_Factura.Tipo_FacturaColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string _Nro__Factura {
                get {
                    try {
                        return ((string)(this[this.tablev_Factura._Nro__FacturaColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Nro. Factura\' in table \'v_Factura\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Factura._Nro__FacturaColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Guid jornadaVentaID {
                get {
                    try {
                        return ((System.Guid)(this[this.tablev_Factura.jornadaVentaIDColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'jornadaVentaID\' in table \'v_Factura\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Factura.jornadaVentaIDColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Guid sucursalID {
                get {
                    try {
                        return ((System.Guid)(this[this.tablev_Factura.sucursalIDColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'sucursalID\' in table \'v_Factura\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Factura.sucursalIDColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Sucursal {
                get {
                    try {
                        return ((string)(this[this.tablev_Factura.SucursalColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Sucursal\' in table \'v_Factura\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Factura.SucursalColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Guid notaPedidoID {
                get {
                    try {
                        return ((System.Guid)(this[this.tablev_Factura.notaPedidoIDColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'notaPedidoID\' in table \'v_Factura\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Factura.notaPedidoIDColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Estado {
                get {
                    try {
                        return ((string)(this[this.tablev_Factura.EstadoColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Estado\' in table \'v_Factura\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Factura.EstadoColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Guid estadoCuentaCorrienteID {
                get {
                    try {
                        return ((System.Guid)(this[this.tablev_Factura.estadoCuentaCorrienteIDColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'estadoCuentaCorrienteID\' in table \'v_Factura\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Factura.estadoCuentaCorrienteIDColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string _Estado_Cta__Cte_ {
                get {
                    try {
                        return ((string)(this[this.tablev_Factura._Estado_Cta__Cte_Column]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Estado Cta. Cte.\' in table \'v_Factura\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Factura._Estado_Cta__Cte_Column] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Plazo_Pago {
                get {
                    try {
                        return ((string)(this[this.tablev_Factura.Plazo_PagoColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Plazo Pago\' in table \'v_Factura\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Factura.Plazo_PagoColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int _Ejercicio_Nro_ {
                get {
                    try {
                        return ((int)(this[this.tablev_Factura._Ejercicio_Nro_Column]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Ejercicio Nro.\' in table \'v_Factura\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Factura._Ejercicio_Nro_Column] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string notaPedidoSuc {
                get {
                    try {
                        return ((string)(this[this.tablev_Factura.notaPedidoSucColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'notaPedidoSuc\' in table \'v_Factura\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Factura.notaPedidoSucColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string notaPedidoNro {
                get {
                    try {
                        return ((string)(this[this.tablev_Factura.notaPedidoNroColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'notaPedidoNro\' in table \'v_Factura\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Factura.notaPedidoNroColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Nota_Pedido {
                get {
                    try {
                        return ((string)(this[this.tablev_Factura.Nota_PedidoColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Nota Pedido\' in table \'v_Factura\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Factura.Nota_PedidoColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsclienteIDNull() {
                return this.IsNull(this.tablev_Factura.clienteIDColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetclienteIDNull() {
                this[this.tablev_Factura.clienteIDColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsapellidoNull() {
                return this.IsNull(this.tablev_Factura.apellidoColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetapellidoNull() {
                this[this.tablev_Factura.apellidoColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsnombresNull() {
                return this.IsNull(this.tablev_Factura.nombresColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetnombresNull() {
                this[this.tablev_Factura.nombresColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsivaIDClienteNull() {
                return this.IsNull(this.tablev_Factura.ivaIDClienteColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetivaIDClienteNull() {
                this[this.tablev_Factura.ivaIDClienteColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsIVANull() {
                return this.IsNull(this.tablev_Factura.IVAColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetIVANull() {
                this[this.tablev_Factura.IVAColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsvendedorIDNull() {
                return this.IsNull(this.tablev_Factura.vendedorIDColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetvendedorIDNull() {
                this[this.tablev_Factura.vendedorIDColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsVendedorNull() {
                return this.IsNull(this.tablev_Factura.VendedorColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetVendedorNull() {
                this[this.tablev_Factura.VendedorColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsautorizadorBonificacionIDNull() {
                return this.IsNull(this.tablev_Factura.autorizadorBonificacionIDColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetautorizadorBonificacionIDNull() {
                this[this.tablev_Factura.autorizadorBonificacionIDColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsAutorizóNull() {
                return this.IsNull(this.tablev_Factura.AutorizóColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetAutorizóNull() {
                this[this.tablev_Factura.AutorizóColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCondición_de_EntregaNull() {
                return this.IsNull(this.tablev_Factura.Condición_de_EntregaColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCondición_de_EntregaNull() {
                this[this.tablev_Factura.Condición_de_EntregaColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IscondicionEntregaIDNull() {
                return this.IsNull(this.tablev_Factura.condicionEntregaIDColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetcondicionEntregaIDNull() {
                this[this.tablev_Factura.condicionEntregaIDColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsestadoFacturaIDNull() {
                return this.IsNull(this.tablev_Factura.estadoFacturaIDColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetestadoFacturaIDNull() {
                this[this.tablev_Factura.estadoFacturaIDColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsmaquinaIDNull() {
                return this.IsNull(this.tablev_Factura.maquinaIDColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetmaquinaIDNull() {
                this[this.tablev_Factura.maquinaIDColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsMáquinaNull() {
                return this.IsNull(this.tablev_Factura.MáquinaColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetMáquinaNull() {
                this[this.tablev_Factura.MáquinaColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsformaPagoIDNull() {
                return this.IsNull(this.tablev_Factura.formaPagoIDColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetformaPagoIDNull() {
                this[this.tablev_Factura.formaPagoIDColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Is_Nro__FacturaNull() {
                return this.IsNull(this.tablev_Factura._Nro__FacturaColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Set_Nro__FacturaNull() {
                this[this.tablev_Factura._Nro__FacturaColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsjornadaVentaIDNull() {
                return this.IsNull(this.tablev_Factura.jornadaVentaIDColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetjornadaVentaIDNull() {
                this[this.tablev_Factura.jornadaVentaIDColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IssucursalIDNull() {
                return this.IsNull(this.tablev_Factura.sucursalIDColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetsucursalIDNull() {
                this[this.tablev_Factura.sucursalIDColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSucursalNull() {
                return this.IsNull(this.tablev_Factura.SucursalColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSucursalNull() {
                this[this.tablev_Factura.SucursalColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsnotaPedidoIDNull() {
                return this.IsNull(this.tablev_Factura.notaPedidoIDColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetnotaPedidoIDNull() {
                this[this.tablev_Factura.notaPedidoIDColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsEstadoNull() {
                return this.IsNull(this.tablev_Factura.EstadoColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetEstadoNull() {
                this[this.tablev_Factura.EstadoColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsestadoCuentaCorrienteIDNull() {
                return this.IsNull(this.tablev_Factura.estadoCuentaCorrienteIDColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetestadoCuentaCorrienteIDNull() {
                this[this.tablev_Factura.estadoCuentaCorrienteIDColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Is_Estado_Cta__Cte_Null() {
                return this.IsNull(this.tablev_Factura._Estado_Cta__Cte_Column);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Set_Estado_Cta__Cte_Null() {
                this[this.tablev_Factura._Estado_Cta__Cte_Column] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPlazo_PagoNull() {
                return this.IsNull(this.tablev_Factura.Plazo_PagoColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPlazo_PagoNull() {
                this[this.tablev_Factura.Plazo_PagoColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Is_Ejercicio_Nro_Null() {
                return this.IsNull(this.tablev_Factura._Ejercicio_Nro_Column);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Set_Ejercicio_Nro_Null() {
                this[this.tablev_Factura._Ejercicio_Nro_Column] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsnotaPedidoSucNull() {
                return this.IsNull(this.tablev_Factura.notaPedidoSucColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetnotaPedidoSucNull() {
                this[this.tablev_Factura.notaPedidoSucColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsnotaPedidoNroNull() {
                return this.IsNull(this.tablev_Factura.notaPedidoNroColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetnotaPedidoNroNull() {
                this[this.tablev_Factura.notaPedidoNroColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsNota_PedidoNull() {
                return this.IsNull(this.tablev_Factura.Nota_PedidoColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetNota_PedidoNull() {
                this[this.tablev_Factura.Nota_PedidoColumn] = System.Convert.DBNull;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class v_FacturaRowChangeEvent : System.EventArgs {
            
            private v_FacturaRow eventRow;
            
            private System.Data.DataRowAction eventAction;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public v_FacturaRowChangeEvent(v_FacturaRow row, System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public v_FacturaRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591