//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.5472
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace CapaPresentacion {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dsCheque")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dsCheque : global::System.Data.DataSet {
        
        private v_ChequeDataTable tablev_Cheque;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public dsCheque() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected dsCheque(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["v_Cheque"] != null)) {
                    base.Tables.Add(new v_ChequeDataTable(ds.Tables["v_Cheque"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public v_ChequeDataTable v_Cheque {
            get {
                return this.tablev_Cheque;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            dsCheque cln = ((dsCheque)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["v_Cheque"] != null)) {
                    base.Tables.Add(new v_ChequeDataTable(ds.Tables["v_Cheque"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tablev_Cheque = ((v_ChequeDataTable)(base.Tables["v_Cheque"]));
            if ((initTable == true)) {
                if ((this.tablev_Cheque != null)) {
                    this.tablev_Cheque.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "dsCheque";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsCheque.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tablev_Cheque = new v_ChequeDataTable();
            base.Tables.Add(this.tablev_Cheque);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializev_Cheque() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dsCheque ds = new dsCheque();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void v_ChequeRowChangeEventHandler(object sender, v_ChequeRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class v_ChequeDataTable : global::System.Data.DataTable, global::System.Collections.IEnumerable {
            
            private global::System.Data.DataColumn columncodigo;
            
            private global::System.Data.DataColumn columncuentaTexto;
            
            private global::System.Data.DataColumn columnclienteTexto;
            
            private global::System.Data.DataColumn columnbancoTexto;
            
            private global::System.Data.DataColumn columnsucursalTexto;
            
            private global::System.Data.DataColumn columnnroCheque;
            
            private global::System.Data.DataColumn columnvencimiento;
            
            private global::System.Data.DataColumn columnimporte;
            
            private global::System.Data.DataColumn columnfirmanteTexto;
            
            private global::System.Data.DataColumn columnbaja;
            
            private global::System.Data.DataColumn columnproveedorTexto;
            
            private global::System.Data.DataColumn columnfechaBaja;
            
            private global::System.Data.DataColumn columnrechazado;
            
            private global::System.Data.DataColumn columnfechaRechazo;
            
            private global::System.Data.DataColumn columncomentariosRechazo;
            
            private global::System.Data.DataColumn columnregistroBLOB;
            
            private global::System.Data.DataColumn columnid;
            
            private global::System.Data.DataColumn columnclienteID;
            
            private global::System.Data.DataColumn columnbancoID;
            
            private global::System.Data.DataColumn columnsucursalID;
            
            private global::System.Data.DataColumn columncuentaID;
            
            private global::System.Data.DataColumn columnfirmanteID;
            
            private global::System.Data.DataColumn columnestadoID;
            
            private global::System.Data.DataColumn columnestadoTexto;
            
            private global::System.Data.DataColumn columnproveedorID;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public v_ChequeDataTable() {
                this.TableName = "v_Cheque";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal v_ChequeDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected v_ChequeDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn codigoColumn {
                get {
                    return this.columncodigo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn cuentaTextoColumn {
                get {
                    return this.columncuentaTexto;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn clienteTextoColumn {
                get {
                    return this.columnclienteTexto;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn bancoTextoColumn {
                get {
                    return this.columnbancoTexto;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn sucursalTextoColumn {
                get {
                    return this.columnsucursalTexto;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn nroChequeColumn {
                get {
                    return this.columnnroCheque;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn vencimientoColumn {
                get {
                    return this.columnvencimiento;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn importeColumn {
                get {
                    return this.columnimporte;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn firmanteTextoColumn {
                get {
                    return this.columnfirmanteTexto;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn bajaColumn {
                get {
                    return this.columnbaja;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn proveedorTextoColumn {
                get {
                    return this.columnproveedorTexto;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn fechaBajaColumn {
                get {
                    return this.columnfechaBaja;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn rechazadoColumn {
                get {
                    return this.columnrechazado;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn fechaRechazoColumn {
                get {
                    return this.columnfechaRechazo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn comentariosRechazoColumn {
                get {
                    return this.columncomentariosRechazo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn registroBLOBColumn {
                get {
                    return this.columnregistroBLOB;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn idColumn {
                get {
                    return this.columnid;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn clienteIDColumn {
                get {
                    return this.columnclienteID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn bancoIDColumn {
                get {
                    return this.columnbancoID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn sucursalIDColumn {
                get {
                    return this.columnsucursalID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn cuentaIDColumn {
                get {
                    return this.columncuentaID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn firmanteIDColumn {
                get {
                    return this.columnfirmanteID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn estadoIDColumn {
                get {
                    return this.columnestadoID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn estadoTextoColumn {
                get {
                    return this.columnestadoTexto;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn proveedorIDColumn {
                get {
                    return this.columnproveedorID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public v_ChequeRow this[int index] {
                get {
                    return ((v_ChequeRow)(this.Rows[index]));
                }
            }
            
            public event v_ChequeRowChangeEventHandler v_ChequeRowChanging;
            
            public event v_ChequeRowChangeEventHandler v_ChequeRowChanged;
            
            public event v_ChequeRowChangeEventHandler v_ChequeRowDeleting;
            
            public event v_ChequeRowChangeEventHandler v_ChequeRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Addv_ChequeRow(v_ChequeRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public v_ChequeRow Addv_ChequeRow(
                        string codigo, 
                        string cuentaTexto, 
                        string clienteTexto, 
                        string bancoTexto, 
                        string sucursalTexto, 
                        string nroCheque, 
                        System.DateTime vencimiento, 
                        decimal importe, 
                        string firmanteTexto, 
                        bool baja, 
                        string proveedorTexto, 
                        System.DateTime fechaBaja, 
                        bool rechazado, 
                        System.DateTime fechaRechazo, 
                        string comentariosRechazo, 
                        string registroBLOB, 
                        System.Guid id, 
                        System.Guid clienteID, 
                        System.Guid bancoID, 
                        System.Guid sucursalID, 
                        System.Guid cuentaID, 
                        System.Guid firmanteID, 
                        System.Guid estadoID, 
                        string estadoTexto, 
                        System.Guid proveedorID) {
                v_ChequeRow rowv_ChequeRow = ((v_ChequeRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        codigo,
                        cuentaTexto,
                        clienteTexto,
                        bancoTexto,
                        sucursalTexto,
                        nroCheque,
                        vencimiento,
                        importe,
                        firmanteTexto,
                        baja,
                        proveedorTexto,
                        fechaBaja,
                        rechazado,
                        fechaRechazo,
                        comentariosRechazo,
                        registroBLOB,
                        id,
                        clienteID,
                        bancoID,
                        sucursalID,
                        cuentaID,
                        firmanteID,
                        estadoID,
                        estadoTexto,
                        proveedorID};
                rowv_ChequeRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowv_ChequeRow);
                return rowv_ChequeRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public virtual global::System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                v_ChequeDataTable cln = ((v_ChequeDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new v_ChequeDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columncodigo = base.Columns["codigo"];
                this.columncuentaTexto = base.Columns["cuentaTexto"];
                this.columnclienteTexto = base.Columns["clienteTexto"];
                this.columnbancoTexto = base.Columns["bancoTexto"];
                this.columnsucursalTexto = base.Columns["sucursalTexto"];
                this.columnnroCheque = base.Columns["nroCheque"];
                this.columnvencimiento = base.Columns["vencimiento"];
                this.columnimporte = base.Columns["importe"];
                this.columnfirmanteTexto = base.Columns["firmanteTexto"];
                this.columnbaja = base.Columns["baja"];
                this.columnproveedorTexto = base.Columns["proveedorTexto"];
                this.columnfechaBaja = base.Columns["fechaBaja"];
                this.columnrechazado = base.Columns["rechazado"];
                this.columnfechaRechazo = base.Columns["fechaRechazo"];
                this.columncomentariosRechazo = base.Columns["comentariosRechazo"];
                this.columnregistroBLOB = base.Columns["registroBLOB"];
                this.columnid = base.Columns["id"];
                this.columnclienteID = base.Columns["clienteID"];
                this.columnbancoID = base.Columns["bancoID"];
                this.columnsucursalID = base.Columns["sucursalID"];
                this.columncuentaID = base.Columns["cuentaID"];
                this.columnfirmanteID = base.Columns["firmanteID"];
                this.columnestadoID = base.Columns["estadoID"];
                this.columnestadoTexto = base.Columns["estadoTexto"];
                this.columnproveedorID = base.Columns["proveedorID"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columncodigo = new global::System.Data.DataColumn("codigo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncodigo);
                this.columncuentaTexto = new global::System.Data.DataColumn("cuentaTexto", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncuentaTexto);
                this.columnclienteTexto = new global::System.Data.DataColumn("clienteTexto", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnclienteTexto);
                this.columnbancoTexto = new global::System.Data.DataColumn("bancoTexto", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnbancoTexto);
                this.columnsucursalTexto = new global::System.Data.DataColumn("sucursalTexto", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnsucursalTexto);
                this.columnnroCheque = new global::System.Data.DataColumn("nroCheque", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnnroCheque);
                this.columnvencimiento = new global::System.Data.DataColumn("vencimiento", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnvencimiento);
                this.columnimporte = new global::System.Data.DataColumn("importe", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnimporte);
                this.columnfirmanteTexto = new global::System.Data.DataColumn("firmanteTexto", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfirmanteTexto);
                this.columnbaja = new global::System.Data.DataColumn("baja", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnbaja);
                this.columnproveedorTexto = new global::System.Data.DataColumn("proveedorTexto", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnproveedorTexto);
                this.columnfechaBaja = new global::System.Data.DataColumn("fechaBaja", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfechaBaja);
                this.columnrechazado = new global::System.Data.DataColumn("rechazado", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnrechazado);
                this.columnfechaRechazo = new global::System.Data.DataColumn("fechaRechazo", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfechaRechazo);
                this.columncomentariosRechazo = new global::System.Data.DataColumn("comentariosRechazo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncomentariosRechazo);
                this.columnregistroBLOB = new global::System.Data.DataColumn("registroBLOB", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnregistroBLOB);
                this.columnid = new global::System.Data.DataColumn("id", typeof(global::System.Guid), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnid);
                this.columnclienteID = new global::System.Data.DataColumn("clienteID", typeof(global::System.Guid), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnclienteID);
                this.columnbancoID = new global::System.Data.DataColumn("bancoID", typeof(global::System.Guid), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnbancoID);
                this.columnsucursalID = new global::System.Data.DataColumn("sucursalID", typeof(global::System.Guid), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnsucursalID);
                this.columncuentaID = new global::System.Data.DataColumn("cuentaID", typeof(global::System.Guid), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncuentaID);
                this.columnfirmanteID = new global::System.Data.DataColumn("firmanteID", typeof(global::System.Guid), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfirmanteID);
                this.columnestadoID = new global::System.Data.DataColumn("estadoID", typeof(global::System.Guid), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnestadoID);
                this.columnestadoTexto = new global::System.Data.DataColumn("estadoTexto", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnestadoTexto);
                this.columnproveedorID = new global::System.Data.DataColumn("proveedorID", typeof(global::System.Guid), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnproveedorID);
                this.columncodigo.MaxLength = 50;
                this.columncuentaTexto.MaxLength = 256;
                this.columnclienteTexto.MaxLength = 256;
                this.columnbancoTexto.MaxLength = 256;
                this.columnsucursalTexto.MaxLength = 256;
                this.columnnroCheque.MaxLength = 255;
                this.columnfirmanteTexto.MaxLength = 256;
                this.columnproveedorTexto.MaxLength = 256;
                this.columncomentariosRechazo.MaxLength = 5000;
                this.columnregistroBLOB.MaxLength = 8000;
                this.columnid.AllowDBNull = false;
                this.columnestadoTexto.MaxLength = 256;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public v_ChequeRow Newv_ChequeRow() {
                return ((v_ChequeRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new v_ChequeRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(v_ChequeRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.v_ChequeRowChanged != null)) {
                    this.v_ChequeRowChanged(this, new v_ChequeRowChangeEvent(((v_ChequeRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.v_ChequeRowChanging != null)) {
                    this.v_ChequeRowChanging(this, new v_ChequeRowChangeEvent(((v_ChequeRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.v_ChequeRowDeleted != null)) {
                    this.v_ChequeRowDeleted(this, new v_ChequeRowChangeEvent(((v_ChequeRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.v_ChequeRowDeleting != null)) {
                    this.v_ChequeRowDeleting(this, new v_ChequeRowChangeEvent(((v_ChequeRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Removev_ChequeRow(v_ChequeRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dsCheque ds = new dsCheque();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "v_ChequeDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class v_ChequeRow : global::System.Data.DataRow {
            
            private v_ChequeDataTable tablev_Cheque;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal v_ChequeRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tablev_Cheque = ((v_ChequeDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string codigo {
                get {
                    try {
                        return ((string)(this[this.tablev_Cheque.codigoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'codigo\' de la tabla \'v_Cheque\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Cheque.codigoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string cuentaTexto {
                get {
                    try {
                        return ((string)(this[this.tablev_Cheque.cuentaTextoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'cuentaTexto\' de la tabla \'v_Cheque\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Cheque.cuentaTextoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string clienteTexto {
                get {
                    try {
                        return ((string)(this[this.tablev_Cheque.clienteTextoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'clienteTexto\' de la tabla \'v_Cheque\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Cheque.clienteTextoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string bancoTexto {
                get {
                    try {
                        return ((string)(this[this.tablev_Cheque.bancoTextoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'bancoTexto\' de la tabla \'v_Cheque\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Cheque.bancoTextoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string sucursalTexto {
                get {
                    try {
                        return ((string)(this[this.tablev_Cheque.sucursalTextoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'sucursalTexto\' de la tabla \'v_Cheque\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Cheque.sucursalTextoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string nroCheque {
                get {
                    try {
                        return ((string)(this[this.tablev_Cheque.nroChequeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'nroCheque\' de la tabla \'v_Cheque\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Cheque.nroChequeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime vencimiento {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tablev_Cheque.vencimientoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'vencimiento\' de la tabla \'v_Cheque\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Cheque.vencimientoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal importe {
                get {
                    try {
                        return ((decimal)(this[this.tablev_Cheque.importeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'importe\' de la tabla \'v_Cheque\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Cheque.importeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string firmanteTexto {
                get {
                    try {
                        return ((string)(this[this.tablev_Cheque.firmanteTextoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'firmanteTexto\' de la tabla \'v_Cheque\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Cheque.firmanteTextoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool baja {
                get {
                    try {
                        return ((bool)(this[this.tablev_Cheque.bajaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'baja\' de la tabla \'v_Cheque\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Cheque.bajaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string proveedorTexto {
                get {
                    try {
                        return ((string)(this[this.tablev_Cheque.proveedorTextoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'proveedorTexto\' de la tabla \'v_Cheque\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Cheque.proveedorTextoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime fechaBaja {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tablev_Cheque.fechaBajaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'fechaBaja\' de la tabla \'v_Cheque\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Cheque.fechaBajaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool rechazado {
                get {
                    try {
                        return ((bool)(this[this.tablev_Cheque.rechazadoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'rechazado\' de la tabla \'v_Cheque\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Cheque.rechazadoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime fechaRechazo {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tablev_Cheque.fechaRechazoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'fechaRechazo\' de la tabla \'v_Cheque\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Cheque.fechaRechazoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string comentariosRechazo {
                get {
                    try {
                        return ((string)(this[this.tablev_Cheque.comentariosRechazoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'comentariosRechazo\' de la tabla \'v_Cheque\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Cheque.comentariosRechazoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string registroBLOB {
                get {
                    try {
                        return ((string)(this[this.tablev_Cheque.registroBLOBColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'registroBLOB\' de la tabla \'v_Cheque\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Cheque.registroBLOBColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Guid id {
                get {
                    return ((global::System.Guid)(this[this.tablev_Cheque.idColumn]));
                }
                set {
                    this[this.tablev_Cheque.idColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Guid clienteID {
                get {
                    try {
                        return ((global::System.Guid)(this[this.tablev_Cheque.clienteIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'clienteID\' de la tabla \'v_Cheque\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Cheque.clienteIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Guid bancoID {
                get {
                    try {
                        return ((global::System.Guid)(this[this.tablev_Cheque.bancoIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'bancoID\' de la tabla \'v_Cheque\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Cheque.bancoIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Guid sucursalID {
                get {
                    try {
                        return ((global::System.Guid)(this[this.tablev_Cheque.sucursalIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'sucursalID\' de la tabla \'v_Cheque\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Cheque.sucursalIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Guid cuentaID {
                get {
                    try {
                        return ((global::System.Guid)(this[this.tablev_Cheque.cuentaIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'cuentaID\' de la tabla \'v_Cheque\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Cheque.cuentaIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Guid firmanteID {
                get {
                    try {
                        return ((global::System.Guid)(this[this.tablev_Cheque.firmanteIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'firmanteID\' de la tabla \'v_Cheque\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Cheque.firmanteIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Guid estadoID {
                get {
                    try {
                        return ((global::System.Guid)(this[this.tablev_Cheque.estadoIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'estadoID\' de la tabla \'v_Cheque\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Cheque.estadoIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string estadoTexto {
                get {
                    try {
                        return ((string)(this[this.tablev_Cheque.estadoTextoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'estadoTexto\' de la tabla \'v_Cheque\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Cheque.estadoTextoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Guid proveedorID {
                get {
                    try {
                        return ((global::System.Guid)(this[this.tablev_Cheque.proveedorIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'proveedorID\' de la tabla \'v_Cheque\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_Cheque.proveedorIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IscodigoNull() {
                return this.IsNull(this.tablev_Cheque.codigoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetcodigoNull() {
                this[this.tablev_Cheque.codigoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IscuentaTextoNull() {
                return this.IsNull(this.tablev_Cheque.cuentaTextoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetcuentaTextoNull() {
                this[this.tablev_Cheque.cuentaTextoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsclienteTextoNull() {
                return this.IsNull(this.tablev_Cheque.clienteTextoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetclienteTextoNull() {
                this[this.tablev_Cheque.clienteTextoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsbancoTextoNull() {
                return this.IsNull(this.tablev_Cheque.bancoTextoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetbancoTextoNull() {
                this[this.tablev_Cheque.bancoTextoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IssucursalTextoNull() {
                return this.IsNull(this.tablev_Cheque.sucursalTextoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetsucursalTextoNull() {
                this[this.tablev_Cheque.sucursalTextoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsnroChequeNull() {
                return this.IsNull(this.tablev_Cheque.nroChequeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetnroChequeNull() {
                this[this.tablev_Cheque.nroChequeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsvencimientoNull() {
                return this.IsNull(this.tablev_Cheque.vencimientoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetvencimientoNull() {
                this[this.tablev_Cheque.vencimientoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsimporteNull() {
                return this.IsNull(this.tablev_Cheque.importeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetimporteNull() {
                this[this.tablev_Cheque.importeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsfirmanteTextoNull() {
                return this.IsNull(this.tablev_Cheque.firmanteTextoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetfirmanteTextoNull() {
                this[this.tablev_Cheque.firmanteTextoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsbajaNull() {
                return this.IsNull(this.tablev_Cheque.bajaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetbajaNull() {
                this[this.tablev_Cheque.bajaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsproveedorTextoNull() {
                return this.IsNull(this.tablev_Cheque.proveedorTextoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetproveedorTextoNull() {
                this[this.tablev_Cheque.proveedorTextoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsfechaBajaNull() {
                return this.IsNull(this.tablev_Cheque.fechaBajaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetfechaBajaNull() {
                this[this.tablev_Cheque.fechaBajaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsrechazadoNull() {
                return this.IsNull(this.tablev_Cheque.rechazadoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetrechazadoNull() {
                this[this.tablev_Cheque.rechazadoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsfechaRechazoNull() {
                return this.IsNull(this.tablev_Cheque.fechaRechazoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetfechaRechazoNull() {
                this[this.tablev_Cheque.fechaRechazoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IscomentariosRechazoNull() {
                return this.IsNull(this.tablev_Cheque.comentariosRechazoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetcomentariosRechazoNull() {
                this[this.tablev_Cheque.comentariosRechazoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsregistroBLOBNull() {
                return this.IsNull(this.tablev_Cheque.registroBLOBColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetregistroBLOBNull() {
                this[this.tablev_Cheque.registroBLOBColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsclienteIDNull() {
                return this.IsNull(this.tablev_Cheque.clienteIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetclienteIDNull() {
                this[this.tablev_Cheque.clienteIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsbancoIDNull() {
                return this.IsNull(this.tablev_Cheque.bancoIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetbancoIDNull() {
                this[this.tablev_Cheque.bancoIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IssucursalIDNull() {
                return this.IsNull(this.tablev_Cheque.sucursalIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetsucursalIDNull() {
                this[this.tablev_Cheque.sucursalIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IscuentaIDNull() {
                return this.IsNull(this.tablev_Cheque.cuentaIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetcuentaIDNull() {
                this[this.tablev_Cheque.cuentaIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsfirmanteIDNull() {
                return this.IsNull(this.tablev_Cheque.firmanteIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetfirmanteIDNull() {
                this[this.tablev_Cheque.firmanteIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsestadoIDNull() {
                return this.IsNull(this.tablev_Cheque.estadoIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetestadoIDNull() {
                this[this.tablev_Cheque.estadoIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsestadoTextoNull() {
                return this.IsNull(this.tablev_Cheque.estadoTextoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetestadoTextoNull() {
                this[this.tablev_Cheque.estadoTextoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsproveedorIDNull() {
                return this.IsNull(this.tablev_Cheque.proveedorIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetproveedorIDNull() {
                this[this.tablev_Cheque.proveedorIDColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class v_ChequeRowChangeEvent : global::System.EventArgs {
            
            private v_ChequeRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public v_ChequeRowChangeEvent(v_ChequeRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public v_ChequeRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
namespace CapaPresentacion.dsChequeTableAdapters {
    
    
    /// <summary>
    ///Represents the connection and commands used to retrieve and save data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.ComponentModel.DataObjectAttribute(true)]
    [global::System.ComponentModel.DesignerAttribute("Microsoft.VSDesigner.DataSource.Design.TableAdapterDesigner, Microsoft.VSDesigner" +
        ", Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
    public partial class v_ChequeTableAdapter : global::System.ComponentModel.Component {
        
        private global::System.Data.SqlClient.SqlDataAdapter _adapter;
        
        private global::System.Data.SqlClient.SqlConnection _connection;
        
        private global::System.Data.SqlClient.SqlCommand[] _commandCollection;
        
        private bool _clearBeforeFill;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public v_ChequeTableAdapter() {
            this.ClearBeforeFill = true;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Data.SqlClient.SqlDataAdapter Adapter {
            get {
                if ((this._adapter == null)) {
                    this.InitAdapter();
                }
                return this._adapter;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal global::System.Data.SqlClient.SqlConnection Connection {
            get {
                if ((this._connection == null)) {
                    this.InitConnection();
                }
                return this._connection;
            }
            set {
                this._connection = value;
                if ((this.Adapter.InsertCommand != null)) {
                    this.Adapter.InsertCommand.Connection = value;
                }
                if ((this.Adapter.DeleteCommand != null)) {
                    this.Adapter.DeleteCommand.Connection = value;
                }
                if ((this.Adapter.UpdateCommand != null)) {
                    this.Adapter.UpdateCommand.Connection = value;
                }
                for (int i = 0; (i < this.CommandCollection.Length); i = (i + 1)) {
                    if ((this.CommandCollection[i] != null)) {
                        ((global::System.Data.SqlClient.SqlCommand)(this.CommandCollection[i])).Connection = value;
                    }
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected global::System.Data.SqlClient.SqlCommand[] CommandCollection {
            get {
                if ((this._commandCollection == null)) {
                    this.InitCommandCollection();
                }
                return this._commandCollection;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool ClearBeforeFill {
            get {
                return this._clearBeforeFill;
            }
            set {
                this._clearBeforeFill = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitAdapter() {
            this._adapter = new global::System.Data.SqlClient.SqlDataAdapter();
            global::System.Data.Common.DataTableMapping tableMapping = new global::System.Data.Common.DataTableMapping();
            tableMapping.SourceTable = "Table";
            tableMapping.DataSetTable = "v_Cheque";
            tableMapping.ColumnMappings.Add("codigo", "codigo");
            tableMapping.ColumnMappings.Add("cuentaTexto", "cuentaTexto");
            tableMapping.ColumnMappings.Add("clienteTexto", "clienteTexto");
            tableMapping.ColumnMappings.Add("bancoTexto", "bancoTexto");
            tableMapping.ColumnMappings.Add("sucursalTexto", "sucursalTexto");
            tableMapping.ColumnMappings.Add("nroCheque", "nroCheque");
            tableMapping.ColumnMappings.Add("vencimiento", "vencimiento");
            tableMapping.ColumnMappings.Add("importe", "importe");
            tableMapping.ColumnMappings.Add("firmanteTexto", "firmanteTexto");
            tableMapping.ColumnMappings.Add("baja", "baja");
            tableMapping.ColumnMappings.Add("proveedorTexto", "proveedorTexto");
            tableMapping.ColumnMappings.Add("fechaBaja", "fechaBaja");
            tableMapping.ColumnMappings.Add("rechazado", "rechazado");
            tableMapping.ColumnMappings.Add("fechaRechazo", "fechaRechazo");
            tableMapping.ColumnMappings.Add("comentariosRechazo", "comentariosRechazo");
            tableMapping.ColumnMappings.Add("registroBLOB", "registroBLOB");
            tableMapping.ColumnMappings.Add("id", "id");
            tableMapping.ColumnMappings.Add("clienteID", "clienteID");
            tableMapping.ColumnMappings.Add("bancoID", "bancoID");
            tableMapping.ColumnMappings.Add("sucursalID", "sucursalID");
            tableMapping.ColumnMappings.Add("cuentaID", "cuentaID");
            tableMapping.ColumnMappings.Add("firmanteID", "firmanteID");
            tableMapping.ColumnMappings.Add("estadoID", "estadoID");
            tableMapping.ColumnMappings.Add("estadoTexto", "estadoTexto");
            tableMapping.ColumnMappings.Add("proveedorID", "proveedorID");
            this._adapter.TableMappings.Add(tableMapping);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitConnection() {
            this._connection = new global::System.Data.SqlClient.SqlConnection();
            this._connection.ConnectionString = global::CapaPresentacion.Properties.Settings.Default.CoalConnectionString;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitCommandCollection() {
            this._commandCollection = new global::System.Data.SqlClient.SqlCommand[1];
            this._commandCollection[0] = new global::System.Data.SqlClient.SqlCommand();
            this._commandCollection[0].Connection = this.Connection;
            this._commandCollection[0].CommandText = @"SELECT codigo, cuentaTexto, clienteTexto, bancoTexto, sucursalTexto, nroCheque, vencimiento, importe, firmanteTexto, baja, proveedorTexto, fechaBaja, rechazado, fechaRechazo, comentariosRechazo, registroBLOB, id, clienteID, bancoID, sucursalID, cuentaID, firmanteID, estadoID, estadoTexto, proveedorID FROM dbo.v_Cheque";
            this._commandCollection[0].CommandType = global::System.Data.CommandType.Text;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [global::System.ComponentModel.DataObjectMethodAttribute(global::System.ComponentModel.DataObjectMethodType.Fill, true)]
        public virtual int Fill(dsCheque.v_ChequeDataTable dataTable) {
            this.Adapter.SelectCommand = this.CommandCollection[0];
            if ((this.ClearBeforeFill == true)) {
                dataTable.Clear();
            }
            int returnValue = this.Adapter.Fill(dataTable);
            return returnValue;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [global::System.ComponentModel.DataObjectMethodAttribute(global::System.ComponentModel.DataObjectMethodType.Select, true)]
        public virtual dsCheque.v_ChequeDataTable GetData() {
            this.Adapter.SelectCommand = this.CommandCollection[0];
            dsCheque.v_ChequeDataTable dataTable = new dsCheque.v_ChequeDataTable();
            this.Adapter.Fill(dataTable);
            return dataTable;
        }
    }
}

#pragma warning restore 1591